### ISSUE TITLE
Same program under ubuntu 18.04 and centOS7

### ISSUE THREAD

**Issue by Pymann** [Yubico/yubihsm-shell#101]
Hi guys, can you help me?

I wrote a golang wrap for some functions from yubihsm2.h, and it works perfectly under Ubuntu 18.04, but does not on centOS7?
There are somehow inconsistencies in processing the capabilites?!

It's easy stuff like importing and generating wrapkeys.

**Comment by Pymann** [comment]
I put the application now into a docker-container and we updated the Linux.kernel of centOS to 4.4, then it works, means the problem is in the lower-layers of centOS, possibly pkcs11,yubilib,libusb ...

**Comment by a-dma** [comment]
Hi, hard to tell what is wrong without more details. Perhaps some permission related changes or even SELinux, but I'm just guessing.

All I can say is enable debug messages, try to get a minimal reproducible failure and then understand why that happens.

**Comment by Pymann** [comment]
Yes, will be next task to enable verbose mode...

I faced some issues with the garbage collection from golang before, in detail c-pointers content is collected, but I reporgrammed alot and also gargabe collection is disabled for yubihsm interactions.

So from this perspective it should be fine.

**Comment by Pymann** [comment]
So I faced this issue now also on Ubuntu 18.04, the wrapkey is randomly not generated because of permissions denied.
When I apply the verbose mode, it always fails:

[LIB - INF 09:34:02.770926] yubihsm.c:4628 (yh_string_to_domains): Domains parsed as 1
[LIB - INF 09:34:02.771046] yubihsm.c:319 (_send_secure_msg): Sending cmd 5b ( 64 Bytes): 5b003d0000617574 685f626f6f740000 0000000000000000 0000000000000000 0000000000000000 0000000000000100 7afee875d3fa2e1d 0000046000013000
[LIB - CRY 09:34:02.771307] yubihsm.c:328 (_send_secure_msg): CBC encrypting ( 80 Bytes): 5b003d0000617574 685f626f6f740000 0000000000000000 0000000000000000 0000000000000000 0000000000000100 7afee875d3fa2e1d 0000046000013000 8000000000000000 0000000000000000
[LIB - CRY 09:34:02.771792] yubihsm.c:329 (_send_secure_msg): IV: 293ee0d426033fdf 02f4d11ee905c086
[LIB - CRY 09:34:02.771912] yubihsm.c:337 (_send_secure_msg): Ciphertext ( 80 Bytes): 68916ae80cdfb2d9 1867a5d83728c52b 4958874a5efc8670 9a2b141eb043676c 112d4a9b406faca6 0787f8986e75bce7 a18876b3402d30f6 8cbad805a1d92744 7ea95b6ce45a7065 83b507e39722b5f9
[LIB - CRY 09:34:02.772368] yubihsm.c:78 (compute_full_mac): Compute MAC (100 Bytes): 3a96a635ab5a053d 2fbe99ecd113fb48 0500590068916ae8 0cdfb2d91867a5d8 3728c52b4958874a 5efc86709a2b141e b043676c112d4a9b 406faca60787f898 6e75bce7a18876b3 402d30f68cbad805 a1d927447ea95b6c e45a706583b507e3 9722b5f9
[LIB - CRY 09:34:02.773208] yubihsm.c:79 (compute_full_mac): Full result is: 0ecb8f5cb854dd05 d6a531cee9869e2f
[LIB - NET 09:34:02.773305] yubihsm.c:92 (send_msg):  SEND >> (03 + 0089) 05 0059 0068916ae80cdfb2 d91867a5d83728c5 2b4958874a5efc86 709a2b141eb04367 6c112d4a9b406fac a60787f8986e75bc e7a18876b3402d30 f68cbad805a1d927 447ea95b6ce45a70 6583b507e39722b5 f90ecb8f5cb854dd 05
[LIB - INF 09:34:02.774099] yubihsm_libusb.c:152 (usb_write): Write of 92 92, err 0
[LIB - INF 09:34:02.774159] yubihsm_libusb.c:176 (usb_read): Doing usb read
[LIB - INF 09:34:02.784156] yubihsm_libusb.c:184 (usb_read): Read, transfer 28
[LIB - NET 09:34:02.784204] yubihsm.c:96 (send_msg):  RECV << (03 + 0025) 85 0019 00043ae448302a4a 938e9d98565aa517 41c02a84a39d6dd9 af
[LIB - CRY 09:34:02.784328] yubihsm.c:78 (compute_full_mac): Compute MAC ( 36 Bytes): 0ecb8f5cb854dd05 d6a531cee9869e2f 85001900043ae448 302a4a938e9d9856 5aa51741
[LIB - CRY 09:34:02.784546] yubihsm.c:79 (compute_full_mac): Full result is: c02a84a39d6dd9af 01254e770f462c2c
[LIB - INF 09:34:02.784646] yubihsm.c:386 (_send_secure_msg): Response MAC successfully verified
[LIB - CRY 09:34:02.784671] yubihsm.c:405 (_send_secure_msg): CBC decrypting ( 16 Bytes): 043ae448302a4a93 8e9d98565aa51741
[LIB - CRY 09:34:02.784773] yubihsm.c:406 (_send_secure_msg): IV: 293ee0d426033fdf 02f4d11ee905c086
[LIB - CRY 09:34:02.784888] yubihsm.c:414 (_send_secure_msg): Plaintext (  4 Bytes): 7f000109
[LIB - ERR 09:34:02.784931] yubihsm.c:2567 (yh_util_generate_wrap_key): Unable to generate key: Wrong permissions for operation (9)
Error: Wrong permissions for operation
[LIB - INF 09:34:02.785082] yubihsm.c:319 (_send_secure_msg): Sending cmd 4a (  8 Bytes): 4a0005d5d8040000
[LIB - CRY 09:34:02.785156] yubihsm.c:328 (_send_secure_msg): CBC encrypting ( 16 Bytes): 4a0005d5d8040000 8000000000000000
[LIB - CRY 09:34:02.785263] yubihsm.c:329 (_send_secure_msg): IV: 20c7ac2856496a19 5152170c9f1de910
[LIB - CRY 09:34:02.785352] yubihsm.c:337 (_send_secure_msg): Ciphertext ( 16 Bytes): ca68de6170c9f2f2 2e4125afb114d35f
[LIB - CRY 09:34:02.785452] yubihsm.c:78 (compute_full_mac): Compute MAC ( 36 Bytes): 0ecb8f5cb854dd05 d6a531cee9869e2f 05001900ca68de61 70c9f2f22e4125af b114d35f
[LIB - CRY 09:34:02.785679] yubihsm.c:79 (compute_full_mac): Full result is: af947a5abe69377f 9cd973580e0a7862
[LIB - NET 09:34:02.785787] yubihsm.c:92 (send_msg):  SEND >> (03 + 0025) 05 0019 00ca68de6170c9f2 f22e4125afb114d3 5faf947a5abe6937 7f
[LIB - INF 09:34:02.786133] yubihsm_libusb.c:152 (usb_write): Write of 28 28, err 0
[LIB - INF 09:34:02.786178] yubihsm_libusb.c:176 (usb_read): Doing usb read
[LIB - INF 09:34:02.796452] yubihsm_libusb.c:184 (usb_read): Read, transfer 28
[LIB - NET 09:34:02.796487] yubihsm.c:96 (send_msg):  RECV << (03 + 0025) 85 0019 00e5689fc4434413 6a14f23637f61c97 ed06b8dc58b861ca 1a
[LIB - CRY 09:34:02.796594] yubihsm.c:78 (compute_full_mac): Compute MAC ( 36 Bytes): af947a5abe69377f 9cd973580e0a7862 85001900e5689fc4 4344136a14f23637 f61c97ed
[LIB - CRY 09:34:02.796761] yubihsm.c:79 (compute_full_mac): Full result is: 06b8dc58b861ca1a 5a82a9337407eac1
[LIB - INF 09:34:02.796851] yubihsm.c:386 (_send_secure_msg): Response MAC successfully verified
[LIB - CRY 09:34:02.796877] yubihsm.c:405 (_send_secure_msg): CBC decrypting ( 16 Bytes): e5689fc44344136a 14f23637f61c97ed
[LIB - CRY 09:34:02.797009] yubihsm.c:406 (_send_secure_msg): IV: 20c7ac2856496a19 5152170c9f1de910
[LIB - CRY 09:34:02.797134] yubihsm.c:414 (_send_secure_msg): Plaintext (  4 Bytes): 7f00010b
[LIB - ERR 09:34:02.797175] yubihsm.c:2348 (yh_util_export_wrapped): Unable to get wrapped object: Object not found (b)
Error: Object not found
Creating exported wrapkey-file: ./exported_wrapkey__0.bin
Closing session.
[LIB - INF 09:34:02.797540] yubihsm.c:319 (_send_secure_msg): Sending cmd 40 (  3 Bytes): 400000
[LIB - CRY 09:34:02.797595] yubihsm.c:328 (_send_secure_msg): CBC encrypting ( 16 Bytes): 4000008000000000 0000000000000000
[LIB - CRY 09:34:02.797690] yubihsm.c:329 (_send_secure_msg): IV: 1fc8a688c5b4c742 c1002640618d1cd2
[LIB - CRY 09:34:02.797793] yubihsm.c:337 (_send_secure_msg): Ciphertext ( 16 Bytes): a48f1c686db7f447 413a57ce0b5c9d64
[LIB - CRY 09:34:02.797913] yubihsm.c:78 (compute_full_mac): Compute MAC ( 36 Bytes): af947a5abe69377f 9cd973580e0a7862 05001900a48f1c68 6db7f447413a57ce 0b5c9d64
[LIB - CRY 09:34:02.798145] yubihsm.c:79 (compute_full_mac): Full result is: 49f6eacb622adccb 246725feb0ae123a
[LIB - NET 09:34:02.798250] yubihsm.c:92 (send_msg):  SEND >> (03 + 0025) 05 0019 00a48f1c686db7f4 47413a57ce0b5c9d 6449f6eacb622adc cb
[LIB - INF 09:34:02.798589] yubihsm_libusb.c:152 (usb_write): Write of 28 28, err 0
[LIB - INF 09:34:02.798633] yubihsm_libusb.c:176 (usb_read): Doing usb read
[LIB - INF 09:34:02.808192] yubihsm_libusb.c:184 (usb_read): Read, transfer 28
[LIB - NET 09:34:02.808229] yubihsm.c:96 (send_msg):  RECV << (03 + 0025) 85 0019 003acf448a00abf7 e7fac3393c09c5ba 48d381d101537214 eb
[LIB - CRY 09:34:02.808347] yubihsm.c:78 (compute_full_mac): Compute MAC ( 36 Bytes): 49f6eacb622adccb 246725feb0ae123a 850019003acf448a 00abf7e7fac3393c 09c5ba48
[LIB - CRY 09:34:02.808564] yubihsm.c:79 (compute_full_mac): Full result is: d381d101537214eb 2c560b1c6a06cdc1
[LIB - INF 09:34:02.808655] yubihsm.c:386 (_send_secure_msg): Response MAC successfully verified
[LIB - CRY 09:34:02.808673] yubihsm.c:405 (_send_secure_msg): CBC decrypting ( 16 Bytes): 3acf448a00abf7e7 fac3393c09c5ba48
[LIB - CRY 09:34:02.808762] yubihsm.c:406 (_send_secure_msg): IV: 1fc8a688c5b4c742 c1002640618d1cd2
[LIB - CRY 09:34:02.808852] yubihsm.c:414 (_send_secure_msg): Plaintext (  3 Bytes): c00000

when I dont use it it sometimes failed, but usually succeds:
sudo ./yubi_sw_signer -a 50947 -p 123456 -gen-wkey -bck-wkey 54744 -domain 1 -label auth_boot
Getting session...
Received session: 0.
Creating new wrapkey...
wrapkey-ID: 53134
label: auth_boot
domain: 1
Creating exported wrapkey-file: ./exported_wrapkey__53134.bin
Closing session.

**Comment by Pymann** [comment]
The Behaviur is also different for authorities, the standard authority never fails.
Created with caps and del_caps, fails:
"reset-device|delete-authentication-key|exportable-under-wrap|export-wrapped|import-wrapped|unwrap-data|wrap-data|generate-asymmetric-key|generate-wrap-key|delete-wrap-key|get-log-entries|put-wrap-key|put-opaque|get-opaque|delete-opaque",
"reset-device|delete-authentication-key|exportable-under-wrap|export-wrapped|import-wrapped|unwrap-data|wrap-data|delete-wrap-key|get-log-entries|put-wrap-key|put-opaque|get-opaque|delete-opaque"

**Comment by Pymann** [comment]
In my eyes you have definitely bug in authority creation, or verification for operations:
When I define it for all doms and all caps, all del_cps its working fine.

**Comment by a-dma** [comment]
Given that the default authentication key always works while other authentication keys throw a permission error, I would try to figure out if there is a permission actually missing on any of those keys. Try reading the various capabilities of the authentication key that you're using.

Generally speaking a *minimal snippet of C code* that reproduces the issue would be ideal.
