### ISSUE TITLE
memory resource leaks in yubihsm-shell CLI tool

### ISSUE THREAD

**Issue by invd** [Yubico/yubihsm-shell#118]
I have found more cases of memory resource leaks similar to the ones reported in #88. Given the context, I do not consider the issues as security-related. The functional impact of the leaks is very low during regular CLI operation.

## Part no. 1
If `parse_configured_connectors()` is called with `n_connectors = 0`, some memory for the list is still assigned:

https://github.com/Yubico/yubihsm-shell/blob/ba7b105f870944b0266e8dfcc2a8532a5a66110a/src/main.c#L1760

However, the default handling in `main()` overwrites the `ctx.connector_list` with new heap memory:
https://github.com/Yubico/yubihsm-shell/blob/ba7b105f870944b0266e8dfcc2a8532a5a66110a/src/main.c#L1927-L1943

Consequently, the cleanup in the `main_exit:` section will not be able to release the originally allocated memory.

## Part no. 2
If `parse_usb_url()` exits with errors, the memory assigned with `char *copy = strdup(url);` is not released:
https://github.com/Yubico/yubihsm-shell/blob/55c3eeee32de39a5473e61884ce21b95eaf8fb0b/lib/lib_util.c#L161-L166

## Part no. 3
As far as I can see, the memory allocated in `parse_configured_pubkeys()` is never released (apart from error handling within the function itself):
https://github.com/Yubico/yubihsm-shell/blob/ba7b105f870944b0266e8dfcc2a8532a5a66110a/src/main.c#L1783
https://github.com/Yubico/yubihsm-shell/blob/ba7b105f870944b0266e8dfcc2a8532a5a66110a/src/main.c#L1791

**Comment by qpernil** [comment]
Fixes in https://github.com/Yubico/yubihsm-shell/pull/134
