### ISSUE TITLE
Invalid argument 6: export-wrapped:import-wrapped (c:capabilities)

### ISSUE THREAD

**Issue by udf2457** [Yubico/yubihsm-shell#14]
yubihsm-shell 1.0.4

`yubihsm> put wrapkey 0 0 "Wrap Key" all export-wrapped,import-wrapped exportable-under-wrap,sign-pkcs,sign-pss,sign-ecdsa,sign-eddsa,decrypt-pkcs,decrypt-oaep,derive-ecdh,sign-hmac,verify-hmac,sign-ssh-certificate,decrypt-otp,create-otp-aead,randomize-otp-aead,rewrap-from-otp-aead-key,rewrap-to-otp-aead-key,sign-attestation-certificate XXXXXXX`
Invalid argument 6: export-wrapped,import-wrapped (c:capabilities)

Even a copy/paste of the examples on the website fail.

**Comment by klali** [comment]
version 2.0.0 was released at https://developers.yubico.com/YubiHSM2/Releases/, please use that version, and the documentation is for that version. Some strings changed (unfortunately) to make more sense.

**Comment by udf2457** [comment]
@klali will try.  But if you say the strings changed, does that mean the docs need updating too (since the copy/paste of website examples also failed for me ?)

**Comment by klali** [comment]
The website has been updated for the syntax in the 2.0.0 version of the software.

**Comment by Stupendoussteve** [comment]
@klali FYI, the page at https://www.yubico.com/products/services-software/download/yubihsm-2-libraries-and-tools/ (main download page from the website) it is still pointing to the 1.0.4 downloads. Explains why I couldn't get things to work though.
