### ISSUE TITLE
YubiHSM sessions are not handled/conveyed correctly in yubishell

### ISSUE THREAD

**Issue by davePham** [Yubico/yubihsm-shell#158]
It is documented on dev.yubico.com that all sessions have an expiration period of 30s.

However, when sessions are allowed to expire, "list sessions" does not appear to reflect any status changes.

To illustrate, here is a transcript of an interaction with the YubiHSM when testing this particular issue:

yubihsm> keepalive off
Session keepalive set up to run every 0 seconds
yubihsm> list sessions
yubihsm> session open 1 password
Created session 0

– Wait for 30+ seconds for the session to elapse –

yubihsm> list objects 0
Failed to list objects: Invalid session
yubihsm> list sessions
Session 0

Note that this does not happen if a session is explicitly closed:

yubihsm> session open 1 password
Created session 0
yubihsm> list sessions
Session 0
yubihsm> session close 0
yubihsm> list sessions
yubihsm>

**Comment by qpernil** [comment]
What version & OS is this on ? I don't see this behaviour. I get the following
list objects 0
Invalid argument 2: 0 (e:session)

**Comment by qpernil** [comment]
In other words, the keepalive is the automatic probe (of all sessions), so when turning that off it won't notice a session is invalid until it tries to use it, whereupon it first probes it, and removes it if it became expired. If that happens it won't be listed anymore. It seems the version you are using is not working like that.

**Comment by qpernil** [comment]
After testing on Windows I get the behaviour I described above there as well

**Comment by qpernil** [comment]
Latest version works as expected, no need to dig further so closing.
