### ISSUE TITLE
Code compilation error on PureOS version 9.0 Amber

### ISSUE THREAD

**Issue by richarya** [Yubico/yubihsm-shell#166]
I had been trying to compile YubiHSM-Shell tool from the source – “https://github.com/Yubico/yubihsm-shell” for PureOS Amber version 9.0.
I downloaded the dependencies, compiled the code, and built the tool, however when I am trying to run “make test” command, 5/26 tests are failing. Below is the link for the test failure image.
![image](https://user-images.githubusercontent.com/81139446/111944037-f75fac00-8a93-11eb-9e8e-f3cb5f776f7e.png)

Can someone please help me resolving the issue?

**Comment by qpernil** [comment]
If you run ctest --output-on-failure in the build directory you will get printouts from the failed tests, which may help to identify the problem.

**Comment by richarya** [comment]
I was able to build the tool on PureOS and it is now working as expected, even after these tests failed. Thank you!

**Comment by richarya** [comment]
I was able to build the tool on PureOS and it is now working as expected, even after these tests failed. Thank you!
