### ISSUE TITLE
Unable to read Asymmetric Key

### ISSUE THREAD

**Issue by naimulhq** [Yubico/yubihsm-shell#177]
I am trying to generate private public key pairs outside of the Yubihsm2 so I could import it to multiple different HSMs. I am running the following commands:
```
openssl genrsa -out private-key.pem 2048

openssl rsa -in private-key.pem -pubout -out public-key.pem
yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> connect
Session keepalive set up to run every 15 seconds
yubihsm> session open 1 password
Created session 0
yubihsm> put asymmetric 0 0 test 1 none rsa-pkcs1-sha256 private-key.pem
Unable to read asymmetric key


```

I am not sure why the key is not being imported. Any advice?

**Comment by a-dma** [comment]
Hi, there are two small issues with the last command:
- there is one extra parameter (the `none`) which makes the input file be `rsa-pkcs1-sha256` which doesn't exist
- the right capability would be `sign-pkcs`

so the correct command to store the key `private-key.pem` would be `put asymmetric 0 0 test 1 sign-pkcs private-key.pem`.

Error messages should be a bit better, ideally something like "Unable to read from FILENAME"

**Comment by naimulhq** [comment]
Going off what Yubico says, https://developers.yubico.com/YubiHSM2/Commands/Put_Asymmetric_Key.html
. I put the none because I thought it would set the capabilities to none and the algorithm would be rsa-pkcs1-sha256. If thats the case, how would I be able to make the asymmetric key exportable under wrap if it doesn't allow me to set values for capabilities.

**Comment by naimulhq** [comment]
Ohhh That makes sense. Thank you very much.
