### ISSUE TITLE
Invalid argument 1: 0 (e:session)

### ISSUE THREAD

**Issue by kobrien** [Yubico/yubihsm-shell#184]
I am trying to perform a hard reset on my yubikey (Edit: YubiHSM), following the instructions here - https://developers.yubico.com/YubiHSM2/Commands/Reset_Device.html

However I am getting an error with `Invalid argument`

I'm building and running with docker
```
docker run -it --rm --name yubihsm-shell -v /dev/bus/usb:/dev/bus/usb --privileged <internal_docker_image_url> /bin/sh

# which yubihsm-shell
/usr/local/bin/yubihsm-shell

# yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> reset 0
Invalid argument 1: 0 (e:session)
yubihsm>

yubihsm> connect
Failed initializing connector http://127.0.0.1:12345: Generic error
```

**Comment by a-dma** [comment]
Are you trying to reset a YubiKey or a YubiHSM? If indeed it is a YubiKey as you say in your message, then this is not the project you want to look at. Use YubiKey Manager instead.

If it is a YubiHSM that you're trying to reset then make sure to have a connector running on a reachable address within your network/container, or run the shell with `yubihsm-shell --connector yhusb://` for direct USB access, in this case make sure to also have adequate permissions on the USB device.

Alternatively, you can just reset the device by touching gold contact for about 10 seconds while plugging in the device.

**Comment by kobrien** [comment]
yes, its a YubiHSM, sorry for the typo.

I'm wondering if docker is the issue here? Going to try install yubihsm-shell directly on the host for now and see if that works (although docker would be preferable)

```
docker exec -it yubihsm-shell /bin/sh
# yubihsm-shell --connector yhusb://
yubihsm> reset 0
Invalid argument 1: 0 (e:session)
```

**Comment by kobrien** [comment]
fails to connect when running from the host

```
<host> :~/yubihsm-shell/build$ yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> connect
Failed initializing connector http://127.0.0.1:12345: Generic error
```

FYI I am able to run `tmkms yubihsm keys list` which works fine

**Comment by kobrien** [comment]
I enabled debug, does this help?
```
yubihsm> connect
[LIB - INF 19:06:17.105783] yubihsm.c:4123 (yh_init_connector): Loading usb backend
[LIB - ERR 19:06:17.106108] yubihsm.c:3975 (load_backend): Failed loading 'libyubihsm_usb.so.2' with error: 'libyubihsm_usb.so.2: cannot open shared object file: No such file or directory'
[LIB - ERR 19:06:17.106298] yubihsm.c:4131 (yh_init_connector): Failed loading the backend
Failed initializing connector yhusb://: Generic error
```

**Comment by a-dma** [comment]
Yes that helps. How did you install `yubihsm-shell`? And what OS are you running on? It looks like you're missing the direct USB backend (libyubihsm_usb.so). Perhaps you're also missing the matching backend for HTTP access?

You can find pre-built packages at https://developers.yubico.com/YubiHSM2/Releases/, those should have everything you need.

To recap, there are three ways of doing this

### Using a connector
Run a connector and make sure it can open the USB device (e.g. with sudo or a udev rule)
```
$ sudo yubihsm-connector -d
```
In another terminal run `yubihsm-shell` and make sure that `libyubihsm_http.so` is available. If you started the connector on a different address, then pass that through the `--connector` option
```
$ yubihsm-shell
Using default connector URL: http://127.0.0.1:12345
yubihsm> connect
Session keepalive set up to run every 15 seconds
yubihsm> session open 1 password
Created session 0
yubihsm> reset 0
Device successfully reset
```

### Using direct USB access
There is no need to run a connector in this case, but `yubihsm-shell` needs permissions to open the USB device (e.g. with sudo or a udev rule) and `libyubihsm_usb.so` has to be available. Start `yubihsm-shell` with the special connector argument like so
```
sudo ./src/yubihsm-shell --connector yhusb://
yubihsm> connect
Session keepalive set up to run every 15 seconds
yubihsm> session open 1 password
Created session 0
yubihsm> reset 0
Device successfully reset
```

### Manually resetting
Insert the device whilst touching the golden rim and wait for it to reset. A good way of seeing that is by following the output of `dmesg`

**Comment by kobrien** [comment]
running on Ubuntu 20.04. I compiled yubihsm-shell from source on the machine but your right it looks like something is missing there, these are the steps I ran for compiling it

```
git clone https://github.com/Yubico/yubihsm-shell.git \
  && cd yubihsm-shell \
  && git checkout 2.2.0 \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make install
```

I've since installed the deb packages directly using the link you provided, and that worked!! (via direct USB access)

```
sudo yubihsm-shell --connector yhusb://
yubihsm> connect
Session keepalive set up to run every 15 seconds
yubihsm> session open 1 password
Created session 0
yubihsm> reset 0
Device successfully reset
```

FYI I actually tried doing a manual hardware reset (3 times) but the keys remained on the device, so not sure why this does not work, hence why I am trying to do it via the CLI route ^ 

Thanks for all your help! Much appreciated!

**Comment by a-dma** [comment]
Glad to hear that it worked in the end.

The steps you mention look good to me, except there's a `make` missing before `make install`, but maybe CMake is clever enough to figure out target dependencies. You may have to re-generate your library cache with `sudo ldconfig` though. Another thing that you can try is to run the tool from the build directory, i.e. `./build/src/yubihsm-shell`, that should find all the dependencies correctly.

I'll close the issue given that the main problem was resolved.
