### ISSUE TITLE
Using a local HSM with the connector

### ISSUE THREAD

**Issue by Xelendor1** [Yubico/yubihsm-shell#186]
I'm trying to use the yubihsm-shell and I managed to install the binaries onto the system.  However I'm not sure how to connect the yubihsm-connector to the hsm2 without the connector daemon running.  Right now I am running

yubihsm-shell --connector http://10.0.7.7:12345

however without the yubihsm-connector daemon, i'm not sure how to actually connect to the yubihsm.

**Comment by qpernil** [comment]
You can use the following
yubihsm-shell -C yhusb:// -P

yhusb:// is the 'url' to connect directly to usb without using the connector
The user you run this with must have access to usb (at least to the YubiHSM device)

-C is short for --connector
-P is to connect to the connector immediately (so you don't have to give the connect command. Only useful for interactive mode)

**Comment by qpernil** [comment]
Closing this now as it is presumably solved. Feel free to open a new issue if that's not the case.
