### ISSUE TITLE
Critical Parameters Missing in the YubiHSM Signed Certificate

### ISSUE THREAD

**Issue by bhaijiyunus** [Yubico/yubihsm-shell#188]
Hi Team Yubico,

We are migrating from Yubikey to YubiHSM to configure multiple CA's inside YubiHSM. I have configured the YubiHSM to work as SubCA which signed the client CSR file. Client CSR signing is successful but after I compared YubiHSM signed certificate with Yubikey signed certificate & I can see some parameters missing & certificate version is different in the YubiHSM signed certificate. Please see below screen shots.

I am trying different configuration options but I am looking someone who can quickly guide me to resolve this **missing parameters & certification version** issue.

![image](https://user-images.githubusercontent.com/13213725/130736989-cc760cbe-cea1-418f-a5ad-6f0d1386975c.png)

 
![image](https://user-images.githubusercontent.com/13213725/130738612-8dd1e43a-a8f1-4b36-aa3b-90ca0019a739.png)

### OpenSSL used on Linux:
* OpenSSL 1.1.1

### OpenSSL command used to sign the CSR with YubiHSM SubCA:
```sh
OPENSSL_CONF=./engine.conf openssl x509 -req -days 7305 -CAkeyform engine -engine pkcs11 -CA yubihsm-crt.pem -in clientcsrfile -CAkey "0:0005" -CAcreateserial -sha256 -outform DER -out clientcsrfile.der
```
### Below is the engine.conf file:
```sh
openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
MODULE_PATH = /usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so

INIT_ARGS = connector=http://localhost:12345
init = 0

# Will keep the PIN common for all slots/domains inside YubiHSM
# TODO: Change this PIN as per final deployment
#PIN Format: "<auth key id><auth key password>"
PIN="0001password"
```

**Comment by aveenismail** [comment]
So the parameters you're missing are Basic constraints, Key Usage, Enhanced Key Usage and Subject Alt Name, and you are communication with the YubiHSM through yubihsm_pkcs11, correct?

When using the YubiKey, did you sign using ykcs11?

**Comment by bhaijiyunus** [comment]
Hi Aveen,

You are right, I am using the YubiHSM with yubihsm_pkcs11 as mentioned in engine.conf file.

Yubikey signed certificate is proven certificate & we are expecting to have similar certificate output from YubiHSM. Yubikey have separate config file where we have only Basic constraints, Key Usage, Enhanced Key Usage and Subject Alt Name & hence these parameters appeared in Yubikey signed certificate.

Question is how we can add these missing parameters in YubiHSM signed certificate? Do I need to modify engine.conf file? Did I missed anything in the above OpenSSL command?

**Comment by bhaijiyunus** [comment]
I am able to add extensions in the certificate file using -extfile option & the required extensions in the configuration file.
```sh
OPENSSL_CONF=./engine.conf openssl x509 -req -days 7305 -CAkeyform engine -engine pkcs11 -CA yubihsm-crt.pem -in clientcsrfile -CAkey "0:0005" -CAcreateserial -sha256 -outform DER -out clientcsrfile.der -extfile ./extension.conf
```
