### ISSUE TITLE
Does YubiHSM 2 & Its SDK Packages Support ARM(to be specific Raspberry Pi board)

### ISSUE THREAD

**Issue by bhaijiyunus** [Yubico/yubihsm-shell#191]
Does YubiHSM 2 & Its SDK Packages support for ARM platform(to be specific Raspberry Pi board)?

**Comment by qpernil** [comment]
Yes, I regularly build on Raspbian (32 bit) and Ubuntu (64 bit) on the raspberry PI.

**Comment by bhaijiyunus** [comment]
Hi @qpernil,

Thanks for reply.
I am using RPi 4 with ubuntu-18.04.5-preinstalled-server-arm64+raspi3.img image installed. Do you have pre-build packages for this image? If available, can you share that packages?

**Comment by qpernil** [comment]
We don't have prebuilt images for that but it should be easy to build from source. 

Here are the packages I've installed (with sudo apt install). You probably don't need them all.

build-essential
make
autoconf
libtool
m4
libssl-dev
pkg-config
check
pcsc-tools
libpcsclite-dev
gengetopt
help2man
opensc
git2cl
valgrind
doxygen
clang

After installing those just do

git clone https://github.com/Yubico/yubihsm-shell

cd yubihsm-shell
mkdir build
cd build
cmake ..
make
make install

**Comment by bhaijiyunus** [comment]
I tried(when I started investigation on YubiHSM) compiling yubihsm-shell on my Ubuntu VM & I will give a try to build on RPi 4. What about the other dependent packages like highlighted below, do we also need to build these pkgs?
![image](https://user-images.githubusercontent.com/13213725/135232565-1bff9f45-aba4-48fa-a996-f7785cf1ddd7.png)

**Comment by qpernil** [comment]
No, those are the ones you will build

**Comment by qpernil** [comment]
If you use usb directly like that you must either run as root or set up udev rules to give normal users access to the YUbiHSM usb device.
