### ISSUE TITLE
Can we store the Cloud credentials inside YubiHSM?

### ISSUE THREAD

**Issue by bhaijiyunus** [Yubico/yubihsm-shell#215]
Hi,

We have one step in the factory provisioning process which will register the device with the cloud & during the device registration process, device hits cloud along with its cloud credentials. 
We are in discussion on how we can securely store & protect the cloud credentials on provision station. In regards with that, we need experts suggestions on, 
- Can we store the cloud credentials inside YubiHSM? 
- If yes, how we can store it?

Regards,
Yunus

**Comment by qpernil** [comment]
I would need a little more details regarding the lifecycle of your device, and what gets provisioned to it. In general I can say that the HSM has the ability to store arbitrary data objects (opaque objects) in a secure manner, and as all communications with the HSM are encrypted they are not revealed anywhere but inside the machine that reads them. It has a limited amount of memory so this is not practical if we are talking about large numbers of objects, or large sized objects. In such cases it is advisable to instead use the HSM to encrypt the data, and in that case the data can be stored in the cloud for example.

**Comment by qpernil** [comment]
I am closing this issue now as it has been inactive for a while. Don't hesitate to open a new issue if needed.
