### ISSUE TITLE
linker flags break build on MacOS

### ISSUE THREAD

**Issue by mouse07410** [Yubico/yubihsm-shell#219]
macOS Big Sur 11.6.1, cmake-3.21.4, Xcode-13.1.

In short:
```
CMake Error at /opt/local/share/cmake-3.21/Modules/CheckLinkerFlag.cmake:46 (if):
  if given arguments:

    "NOT" "_lang" "IN_LIST" "_supported_languages"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/SecurityFlags.cmake:14 (check_linker_flag)
  CMakeLists.txt:31 (include)
```

Removing (or commenting out) those offending flags remedied the situation.

Also, as we're building `yubihsm-shell` against OpenSSL-3.0.0, there's a ton of DEPRECATED warnings, so had to disable `-Werror` flag (another option was to force build against OpenSSL-1.1.1).

```diff
diff --git a/cmake/SecurityFlags.cmake b/cmake/SecurityFlags.cmake
index a6637fb..ffaa36e 100644
--- a/cmake/SecurityFlags.cmake
+++ b/cmake/SecurityFlags.cmake
@@ -10,12 +10,13 @@ if (CMAKE_C_COMPILER_ID STREQUAL "Clang" OR
     CMAKE_C_COMPILER_ID STREQUAL "GNU")
 
     check_c_compiler_flag("-fstack-protector-all" HAVE_STACK_PROTECTOR_ALL)
-    if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
-        check_linker_flag(C "-Wl,-z,relro,-z,now" HAVE_RELRO)
-        check_linker_flag(C "-Wl,-z,noexecstack" HAVE_NOEXECSTACK)
-    endif()
+    #if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
+    #    check_linker_flag(C "-Wl,-z,relro,-z,now" HAVE_RELRO)
+    #    check_linker_flag(C "-Wl,-z,noexecstack" HAVE_NOEXECSTACK)
+    #endif()
 
-    add_compile_options (-Wall -Wextra -Werror)
+    add_compile_options (-Wall -Wextra)
+    #add_compile_options (-Werror)
     add_compile_options (-Wformat -Wformat-nonliteral -Wformat-security)
     add_compile_options (-Wshadow)
     add_compile_options (-Wcast-qual)
```

and likewise in `CMakeLists.txt`. Also, there I had to add `NOT` to the condition:
```
+  if (NOT CMAKE_C_COMPILER_ID MATCHES Clang)
+    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wl,-z,relro,-z,now")
+  endif ()
```

**Comment by aveenismail** [comment]
The `Unknown arguments specified` error looks strange, and it looks like it's originating from a cmake internal file. Is it possible to update the cmake version and see if that helps?

yubihsm-shell is indeed built and tested with OpenSSL 1.1. If you use the official Mac installer for yubihsm-shell, libcrypto 1.1 is included in the binaries. The reason we are still building with OpenSSL 1.1 is that OpenSSL 3.0 is still too new. Also, we treat all warnings as errors (flag `-Werror`) to ensure the quality of the code

**Comment by mouse07410** [comment]
> it looks like it's originating from a cmake internal file.

Yes it is.

> Is it possible to update the cmake version and see if that helps?

```sh
$ cmake --version
cmake version 3.21.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Alas, no it isn't. Though I find it strange that there'd be such a big difference between 3.21.4 that I'm using, and 3.22.1 that's the latest available.

Please consider addressing this.

>  If you use the official Mac installer for yubihsm-shell, libcrypto 1.1 is included in the binaries

As I explained elsewhere, I **cannot** use the binary installer, because it "pollutes"  `/usr/local` with conflicting (with my installation) header files and libraries - thus breaking other existing applications and source builds. Your installer is fine for a system that doesn't run anything else.

> The reason we are still building with OpenSSL 1.1 is that OpenSSL 3.0 is still too new

Yes it is too new - but it's the official OpenSSL level now.  Thus, it seems reasonable to clean up the source to make it build with OpenSSL-3.0 as well. Your binary installer may stay with 1.1.1 (hopefully, not 1.1!), if you prefer it.

> we treat all warnings as errors (flag `-Werror`) to ensure the quality of the code

In general, so do I. In hits case, however, disabling `-Werror` was the only way to get `yubihsm-shell` built against OpenSSL-3.0.

**Comment by qpernil** [comment]
Hello,

I would like to ask if the problems you saw are still there with the latest master ? I.e. 0ca58bfaa1a20d8b0494fe1a9d998d462f3362c5.

**Comment by mouse07410** [comment]
> the problems you saw are still there with the latest master?

It looks like the linker-flags-related problems are addressed by the latest master. Thanks!

`-Werror` remains, because I'm linking against OpenSSL-3.0.1 - so there are plenty of warnings about "deprecated" methods. But I guess you'd get to cleaning this up after the Holidays?

**Comment by qpernil** [comment]
https://github.com/Yubico/yubihsm-shell/pull/228 should address that issue. Thanks for testing.

**Comment by mouse07410** [comment]
@qpernil one thing more. Current build still produces compiler warnings with `clang`:
```
.  .  .  .  .
[ 24%] Built target test_usb_url
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
[ 25%] Built target yubihsm_usb
[ 26%] Linking C shared library libyubihsm.dylib
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
.  .  .  .  .
```

The cause - presence of `-pie` flag that (apparently?) is not used during compilation (it's a linker flag, right? and `-fpie` is compiler flag?).

**Comment by qpernil** [comment]
Yes we have something similar in the works

**Comment by qpernil** [comment]
I have merged a fix for this, see https://github.com/Yubico/yubihsm-shell/pull/231
