### ISSUE TITLE
Unrecognized signature on the 2.3.0 tarball from developers.yubico.com

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubihsm-shell#223]
The tarball 2.3.0 is not signed with any key listed in the following page:

https://developers.yubico.com/Software_Projects/Software_Signing.html

but instead with A8CE167914EEE232B9237B5410CAC4962E03C7CC.

Can you verify it is one of your keys and add it to the above page?

**Comment by aveenismail** [comment]
Thank you for properly verifying the signatures. 

The listed keys on https://developers.yubico.com/Software_Projects/Software_Signing.html are correct. I have, however, updated my signing sub keys few months ago and it probably just needs updating on your end. See tex https://keyserver.ubuntu.com/pks/lookup?search=aveen.ismail%40yubico.com&fingerprint=on&op=index

**Comment by Jakuje** [comment]
Thank you for the answer.  You are right, I did not pull your new keys before checking. Now it works fine.
