### ISSUE TITLE
command "echo" doesn't work.

### ISSUE THREAD

**Issue by hyerim-kim** [Yubico/yubihsm-shell#23]
Hello, 

I'm learning the [ quick_start_tutorial](https://developers.yubico.com/YubiHSM2/Usage_Guides/YubiHSM_quick_start_tutorial.html) .
But, "echo" example in[ quick_start_tutorial](https://developers.yubico.com/YubiHSM2/Usage_Guides/YubiHSM_quick_start_tutorial.html) doesn't work.
When I try to excute the example, I got this error :
```
yubihsm> echo MEUCIQDrBqS04LN5YdyWGiD4iaEjfl1dn+W4cl97uMMXDpoaiQIgEBe/G/FgP4cumnO3K2XWToAnPvnuVDOnqHPiuUS0q5g= >signature.b64
Invalid argument 1: MEUCIQDrBqS04LN5YdyWGiD4iaEjfl1dn+W4cl97uMMXDpoaiQIgEBe/G/FgP4cumnO3K2XWToAnPvnuVDOnqHPiuUS0q5g= (e:session)
```

How can I store a signature as it is in a temporary file ?

**Comment by a-dma** [comment]
That is not a `yubihsm-shell` command, but a command to run in your terminal. Note the `$` sign at the beginning of the line to signify the prompt.

**Comment by hyerim-kim** [comment]
@a-dma OMG, I couldn't recognize '$'. Thank you for your reply!
