### ISSUE TITLE
Failed to send DECRYPT PKCS1 command: Unable to verify MAC

### ISSUE THREAD

**Issue by hsellik** [Yubico/yubihsm-shell#242]
Hi,

Upgrading from 2021.08 -> 2021.12, I have been experiencing issues with YubiHSM 2 RSA decryption. It works for some time, but then I start to recieve an error in Java code when performing RSA decryption:
`sun.security.pkcs11.wrapper.PKCS11Exception: CKR_FUNCTION_FAILED`

From the yubihsm 2 debug logs I can see the following:
```
[P11 - INF 07:41:52.696310] yubihsm_pkcs11.c:2728 (C_DecryptInit): RSA decryption requested
[P11 - INF 07:41:52.696312] yubihsm_pkcs11.c:2849 (C_DecryptInit): Out
[P11 - INF 07:41:52.696320] yubihsm_pkcs11.c:2866 (C_Decrypt): In
[P11 - INF 07:41:52.696321] yubihsm_pkcs11.c:2913 (C_Decrypt): The size of the data will be 245
[P11 - INF 07:41:52.696322] yubihsm_pkcs11.c:2931 (C_Decrypt): Sending 256 bytes to decrypt
[P11 - INF 07:41:52.696323] yubihsm_pkcs11.c:2947 (C_Decrypt): Using key 1e15
[LIB - NET 07:41:52.696326] yubihsm.c:440 (send_encrypted_msg):  SEND >> ...
[LIB - NET 07:41:52.696358] yubihsm.c:352 (send_authenticated_msg):  SEND >> ...
[LIB - NET 07:41:52.696448] yubihsm.c:289 (send_msg):  SEND >> ...
[LIB - NET 07:41:52.709973] yubihsm.c:296 (send_msg):  RECV << ...
[LIB - NET 07:41:52.709982] yubihsm.c:404 (send_authenticated_msg):  RECV << ...
[LIB - ERR 07:41:52.709984] yubihsm.c:474 (send_encrypted_msg): send_authenticated_msg Unable to verify MAC
[LIB - ERR 07:41:52.709988] yubihsm.c:2398 (yh_util_decrypt_pkcs1v1_5): Failed to send DECRYPT PKCS1 command: Unable to verify MAC
[P11 - ERR 07:41:52.709989] util_pkcs11.c:2571 (perform_decrypt): Decryption failed: Unable to verify MAC
[P11 - ERR 07:41:52.709992] yubihsm_pkcs11.c:2952 (C_Decrypt): Unable to decrypt data
```

Any idea what could be causing this?

Best regards,
Hendrig

**Comment by qpernil** [comment]
This looks like you are running into an issue with session reconnects in libyubihsm, the library used by yubihsm_pkcs11 responsible for the encrypted communication with the HSM. The HSM has an idle timeout of 30s, and the library has an automatic session recreation function if the hsm times out due to inactivity. Unfortunately a regression made this functionality inoperative in the december release. A new release that fixes this will be out very soon.
Please try that release, or let me know if you are positive your application is never inactive for that period of time.
Best regards

**Comment by qpernil** [comment]
The release that fixes this is now out. Let me know if it fixes this issue.
Sorry for the inconvenience.

**Comment by hsellik** [comment]
@qpernil , are there any plans to release 2.3.1 under official releases? https://developers.yubico.com/YubiHSM2/Releases/

**Comment by aveenismail** [comment]
@hsellik 2.3.1 was released in February and is available here: https://developers.yubico.com/yubihsm-shell/Releases/ (it does contain the fix for this bug)

**Comment by hsellik** [comment]
My bad, I was searching for this under YubiHSM 2 SDK release.

**Comment by aveenismail** [comment]
@hsellik No problem :-). Usually, we do release under YubiHSM 2 SDK, but we are trying to separate the releases for the different components to make for easy maintenance. There will still be SDK releases when there are security issues to address, but more releases will be done as separate components
