### ISSUE TITLE
Using an RSA-4096 key with an exponent of 3 on a YubiHSM2

### ISSUE THREAD

**Issue by TonyDevC1** [Yubico/yubihsm-shell#249]
I've seen in the documentation that the YubiHSM2 works with RSA-4096 keys with an exponent of 65537. Is this fixed, or can we use a key with an exponent of 3? Ideally it would be good if the YubiHSM2 could generate a key with an exponent of 3. However if this is not possible, then would it work if we imported a key with an exponent of 3?

I realise that the signature would not be as strong, but this would allow us to continue supporting a legacy application.

Regards,
Tony.

**Comment by a-dma** [comment]
Unfortunately it won't. Neither key generation nor key import will support e = 3.

If you try to import a key through `yubihsm-shell` or using `yubihms-pkcs11` you will receive an error if your key has a public exponent other than 65537.

**Comment by TonyDevC1** [comment]
And again... thank you for the clarification.

Regards,
Tony.
