### ISSUE TITLE
Using YubiHSM2 With OpenSSL on Windows with Cygwin

### ISSUE THREAD

**Issue by dustt411** [Yubico/yubihsm-shell#250]
Hello,
Not sure if this is the correct place to put this, but I've been running into some issues getting my YubiHSM2 running in Cygwin  with openssl. I followed: https://github.com/Yubico/developers.yubico.com/blob/master/content/YubiHSM2/Usage_Guides/OpenSSL_with_pkcs11_engine.adoc

1. Installed the Yubihsm-shell and connector. 
2. Got the latest cygwin installer from https://www.cygwin.com/setup-x86_64.exe
2. Installed cygwin - updated OpenSSL to latest. 
3. Tried to follow https://github.com/OpenSC/libp11/blob/master/INSTALL.md - ran into build errors.
4. Cheated and got the pre-built dlls at https://github.com/OpenSC/libp11/releases/download/libp11-0.4.11/libp11-0.4.11-windows.zip 
5. Edited openssl.cnf with the following:
openssl_conf = openssl_init

[openssl_init]
engines=engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = C:/Users/ITSAMEMARIO/pkcs11/pkcs11.dll
MODULE_PATH = C:/Users/ITSAMEMARIO/pkcs11/YubiHSM_Shell/bin/pkcs11/yubihsm_pkcs11.dll
INIT_ARGS = connector=http://127.0.0.1:12345
init = 0

6. Added YubiHSM Shell/bin to my path in cygwin
7. Created an asymmetric key on the YubiHSM2 in slot 2 (ECP256) - This works fine in Cygwin. 
8. Self Signed a certificate, for the key created in step 7, using openssl ($ openssl req -new -x509 -nodes -days 3650 -out myCert.pem -engine pkcs11 -keyform engine -key 0:0002)   - NOTE this worked fine showing cygwin and openssl can access the YubiHSM2.
9. Using Openssl created another key and CSR for that key (newKey.csr)
10. Tired to sign the csr from step 9 with the key stored on the YubiHSM2 ($ openssl x509 -req -in newKey.csr -CA myCert.pem -CAkeyform engine -engine pkcs11 -CAkey 0:0002 -out newKey.pem -CAcreateserial -sha256

Here are the results I get

Getting CA Private Key
CA certificate and CA private key do not match
34359738384:error:10071065:elliptic curve routines:EC_POINT_cmp:incompatible objects:crypto/ec/ec_lib.c:960:
34359738384:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:crypto/evp/p_lib.c:93:
34359738384:error:10071065:elliptic curve routines:EC_POINT_cmp:incompatible objects:crypto/ec/ec_lib.c:960:
34359738384:error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch:crypto/x509/x509_cmp.c:303:

I can add debug to the yubi connector and I clearly see that openssl is reading out the public key from the YubiHSM2. If I use the YubiHSM Shell to read the public key (off the YubiHSM2) and use openSSL to read the public key out of the cert they are the same. Yet when I try to sign the CSR I get this error. Any thoughts?

Note the same issue occurs if I use MSYS. But if I use mingw64 or windows powershell it works fine. All environments are using the same pkcs11.dll and yubihsm_pkcs11.dll
[debug.txt](https://github.com/Yubico/developers.yubico.com/files/8064897/debug.txt)
Show the debug output when running the openssl command

**Comment by a-dma** [comment]
hi,

what kind of key did you create in step 9? Still a p256 key or did you use a different curve? Same OpenSSL setup?

Things seem to be working as expected in general, so this makes me suspect that something is up with OpenSSL. Perhaps something is inadvertently linking again a different library or has a statically linked version?
Out of curiosity, would you be able to do the same with an RSA key?

**Comment by qpernil** [comment]
Openssl compares the CA private key with the CA certificate, is it possible those do not match ? For EC keys it compares EC parameters as well.

**Comment by dustt411** [comment]
@a-dma 
> hi,
> 
> what kind of key did you create in step 9? Still a p256 key or did you use a different curve? Same OpenSSL setup?
> 
> Things seem to be working as expected in general, so this makes me suspect that something is up with OpenSSL. Perhaps something is inadvertently linking again a different library or has a statically linked version? Out of curiosity, would you be able to do the same with an RSA key?

Created an ECC key in step 9. 

Would you like me to try an RSA key for step 9, or are you saying RSA key in step 7

**Comment by dustt411** [comment]
@qpernil 

> Openssl compares the CA private key with the CA certificate, is it possible those do not match ? For EC keys it compares EC curve parameters as well.

I have verified that the public key in the cert and on the YubiHSM2 match. Also the exact same process works fine with mingw64. Thus I don't think the issue is with the key. I think as @a-dma said it is probably related to something in OpenSSL in cygwin.

**Comment by dustt411** [comment]
@a-dma 

I tried a couple of different combinations and got strange results:

Root Key               Signed Key (csr)              Result
ECC                       ECC                                  - "CA certificate and CA private key do not match"
ECC                       RSA                                 - doesn't even try to use YUBI, last thing openssl prints is "engine "pkcs11" set"
RSA                       ECC                                 - Works
RSA                       RSA                                 - doesn't even try to use YUBI, last thing openssl prints is "engine "pkcs11" set"

**Comment by dustt411** [comment]
Another fun fact with OpenSSL on cygwin I run into trouble generating CSRs for RSA keys, but not ECC keys.

- openssl req -out ecckey.csr -key ecc.key -new -sha256   =>works
- openssl req -out rsakey.csr -key rsa.key -new -sha256 => runs but no files are created 

openssl on cygwin is starting to smell a little funny, because these commands do not use the YUBI at all.

**Comment by a-dma** [comment]
Interesting results. I see you have created the config file, but how are you instructing OpenSSL to use it? Are you exporting the environment variable `OPENSSL_CNF` or alternatively passing `-config filename` to the various commands you're executing?

If debugging for `yubihsm_pkcs11` is enabled and it isn't printing anything then yes it sounds like OpenSSL is not trying to use the module.

Perhaps try running something like `openssl engine -t -c pkcs11` to see what OpenSSL thinks it has been correctly configured.

**Comment by qpernil** [comment]
I imagine this could run into trouble because cygwin essentially builds stuff for Unix, and you have installed yubihsm-shell for Windows. yubihsm-pkcs11 has a dependency on libcrypto from OpenSSL (for Windows) but since you are loading it from OpenSSL command line (for cygwin) it will get that version which may not work. Also, it could well be a different version than the one it's build with. To top it off we ran into incompatibilities in this scenario before even on a pure Linux environment because of the way openssl (libcrypto) was being initialized both bit the openssl command line and the yubihsm_pkcs11.dll

**Comment by qpernil** [comment]
I will close this issue now due to lack of activity. Please open a new issue if needed.
