### ISSUE TITLE
pkcs11 detect when connection to connector fails

### ISSUE THREAD

**Issue by hsellik** [Yubico/yubihsm-shell#267]
Hi,

Using the PKCS#11 module with Java and while I do successfully load the necessary information to memory to communicate with the HSM, things are not very obvious when the connection drops to the HSM and I try to decrypt something.

I get an error: `PKCS11Exception: CKR_FUNCTION_FAILED`.

Is there a way for the PKCS#11 module to throw something better in case the connection drops? Not sure if this is more about my PKCS#11 provider or something that can be done on the module side.

**Comment by qpernil** [comment]
You can set YUBIHSM_PKCS11_DBG, YUBIHSM_PKCS11_DINOUT and YUBIHSM_LIB_DBG environment variables, or set the following in your ./yubihsm_pkcs11.conf file:
connector=http://localhost:12345
debug
libdebug
dinout

That will print out more info about what is going on to stderr (or another file you specify).
The PKCS11 implementation itself can only return error codes, which are translated to exceptions by the Java wrapper, so we can't do anything about what exceptions are thrown (except by returning different error codes).

**Comment by hsellik** [comment]
Perhaps something like CKR_SESSION_CLOSED error code would be sufficient in this case? At least it's a pointer that it's not about the key nor the data one is trying to encrypt. Not very familiar if the codes can be used this way.

The problem is that I have encountered numerous issues and I always get CKR_FUNCTION_FAILED error code. It really doesn't say anything to me and I always end up with the debug options you mentioned, which wastes time. Not convinced that this is the way it should be.

**Comment by qpernil** [comment]
https://github.com/Yubico/yubihsm-shell/pull/279 will improve error reporting.

**Comment by hsellik** [comment]
That's a great improvement, thanks!

**Comment by qpernil** [comment]
#279 should now report better error messages, are you able to build and test from that branch ?

**Comment by qpernil** [comment]
I will now close this issue as fixed, please open a new one if issues persist.
