### ISSUE TITLE
YubiHSM 2 USER CREATION Issue....Need Help

### ISSUE THREAD

**Issue by zhdhasn** [Yubico/yubihsm-shell#269]
Hello, 
Can I create user in yubihsm-shell ?

and Can I provide permission to created users.

and how can I create user.

Please help me

**Comment by zhdhasn** [comment]
How can I set auth PIN in YubiHSM2 ?
Please help me

**Comment by qpernil** [comment]
Both of these concepts are represented by authentication keys in the yubihsm. The 'user id' is the key id of that authentication key, and the 'pin' is the password used to authenticate with that key. When an authentication key is created it is bestowed with a set of capabilities that represent the set of commands than can be performed in a session that was created using that authentication key. A session also encrypt all traffic to the HSM, end-to-end. A default authentication key with id 1 and all capabilites is created after a reset of the HSM (which also erases all keys). 

You can find comprehensive documentation here: https://developers.yubico.com/YubiHSM2/Component_Reference/yubihsm-shell/

Have a look and let me know if there are any specific question you can't find the answer to.

**Comment by qpernil** [comment]
I'm closing this issue now, please feel free to open a new issue for any follow-up questions.
