### ISSUE TITLE
GCC9 build issues with [-Werror=vla-larger-than=]

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubihsm-shell#27]
The GCC9 introduced some checks that fail to build the testsuite:

```
/builddir/build/BUILD/yubihsm-shell-2.0.0/pkcs11/tests/ecdh_derive_test.c: In function 'main':
/builddir/build/BUILD/yubihsm-shell-2.0.0/pkcs11/tests/ecdh_derive_test.c:368:17: error: variable-length array bound is unknown [-Werror=vla-larger-than=]
  368 |   unsigned char ecdh1_bytes[ecdh1_len]; // public key in DER
      |                 ^
/builddir/build/BUILD/yubihsm-shell-2.0.0/pkcs11/tests/ecdh_derive_test.c:419:41: error: variable-length array bound is unknown [-Werror=vla-larger-than=]
  419 |   unsigned char ecdh1_value[ecdh1_len], ecdh2_value[ecdh2_len];
      |                                         ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/cc returned 1 exit status
```

I am not decided whether this is a bug in yubihsm-shell or in gcc since many other uses of VLA are fine for GCC (probably the lenght are bounded by some constants?), but I am attaching a patch that I used to make the things build using dynamic allocation (I can do a PR if you would be willing to accept this change):

https://src.fedoraproject.org/rpms/yubihsm-shell/blob/master/f/yubihsm-shell-2.0.0-gcc9.patch

Otherwise, it is mostly for reference for others who might hit build issues with the new GCC9.

https://bugzilla.redhat.com/show_bug.cgi?id=1676257#c4

**Comment by a-dma** [comment]
Thanks for the report. I think a VLA in that test is unnecessary and dynamically allocating is not worth the hassle. I've pushed a small diff to use a static buffer instead.

Let me know if that works for you.

**Comment by Jakuje** [comment]
Verified with gcc9 and it is happy with this construction. Thank you for the prompt reaction.
