### ISSUE TITLE
eddsa support for yubihsm_pkcs11.so

### ISSUE THREAD

**Issue by xenyou** [Yubico/yubihsm-shell#270]
Hi, I'm using OpenSC pkcs11-tool command.
And I noticed that I can not create keypair for eddsa with yubihsm2.

```
# pkcs11-tool --module /usr/lib/x86_64-linux-gnu/pkcs11/yubihsm_pkcs11.so --login --pin 0001password --keypairgen --key-type ec:edwards25519
Using slot 0 with a present token (0x0)
error: Generate EC key mechanism 1055 not supported
Aborting.
```

Will it be supported in future version?

**Comment by qpernil** [comment]
That's a pkcs#11 3.0 mechanism, but it seems pkcs11-tool is happy to apply it even if the pkcs#11 module reports only 2.4 support. There is a draft pkcs11 3.0 branch in the repo called pkcs11-3_0 that now contains a first stab at supporting ed25519 keygen, key import and signing. I may cherry-pick that change to the non-3.0 branch as well if requested.

**Comment by xenyou** [comment]
Thanks for replying.
I've just confirmed to generate ed25519 keypair with pkcs11-3_0 branch.

BTW, sign/verify with EDDSA still not implemented on the branch?

```
pkcs11-tool --module /usr/local/lib/pkcs11/yubihsm_pkcs11.so --login --pin 0001password --sign -m EDDSA -i data -o data.sig --id 1260
Using slot 0 with a present token (0x0)
Using signature algorithm EDDSA
error: PKCS11 function C_SignInit failed: rv = CKR_MECHANISM_INVALID (0x70)
Aborting.
```

**Comment by qpernil** [comment]
This branch is just a draft, and EDDSA signing is currently implemented through the CKM_ECDSA mechanism. A fix for this is in the works, but will take a little while because of vacation times. EDDSA verification currently doesn't work at all.

**Comment by qpernil** [comment]
The branch has been updated to require CKM_EDDSA for ed25519 keys. I think there might still be a padding bug for eddsa signing, and verification still doesn't work.

**Comment by qpernil** [comment]
The pkcs11-3_0 branch should now support both signing and verification with EDDSA (only ed25519 supported, as that is all the HSM supports). Feel free to test and I'd appreciate any feedback.

**Comment by qpernil** [comment]
I'm assuming the hooray emoji means this issue is solved, hence Im closing it. Please create a new issue if needed.

**Comment by xenyou** [comment]
Sorry for the late reply. I've just confirmed that it now can sign/verify with EDDSA.

```
root@7d0a473dad0e:/var/work/btest1/priv# pkcs11-tool --module /usr/local/lib/pkcs11/yubihsm_pkcs11.so  --pin 0001piyopiyo  --sign -m EDDSA -i data -o data.sig --id 645c
Using slot 0 with a present token (0x0)
Using signature algorithm EDDSA

root@7d0a473dad0e:/var/work/btest1/priv# pkcs11-tool --module /usr/local/lib/pkcs11/yubihsm_pkcs11.so  --pin 0001piyopiyo  --verify -m EDDSA  --signature-file data.sig -i data
Using slot 0 with a present token (0x0)
Using signature algorithm EDDSA
Signature is valid
```
