### ISSUE TITLE
Keep receiving a wrong permissions for operation error

### ISSUE THREAD

**Issue by hillbillyhacker** [Yubico/yubihsm-shell#287]
Im trying to reset the YubiHSM 2 (or change the password) device remotely since the Server is 20miles away. The reason being is  I thought i copied a generated password in there but it seems to be blank. I can open a session and perform just about anything else except a reset or change auth

I keep receiving:
Wrong permission for operation

**Comment by qpernil** [comment]
There are specific capabilities needed to perform any operation on the HSM so it would seem most likely that the auth key you are using doesn't have the required ones (change-authentication-key and reset-device). You can verify what capabilities it has by performing a get objectinfo <session> <key id> command where <key id> is the one you used when loggin in.

**Comment by qpernil** [comment]
Any feedback on this ? Thx!

**Comment by qpernil** [comment]
Closing this as resolved now. Feel free to open a new issues if needed.
