### ISSUE TITLE
pkcs11: Support for symmetric encryption, AES-ECB and AES-CBC is missing

### ISSUE THREAD

**Issue by gilweis** [Yubico/yubihsm-shell#315]
$ pkcs11-tool --module yubihsm_pkcs11.so  -I
Cryptoki version 2.40
Manufacturer     Yubico (www.yubico.com)
Library          YubiHSM PKCS#11 Library (ver 2.40)
Using slot 0 with a present token (0x0)

$ pkcs11-tool --module yubihsm_pkcs11.so -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  RSA-PKCS, keySize={2048,4096}, hw, encrypt, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  SHA256-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  SHA384-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  SHA512-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA1-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA256-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA384-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA512-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={2048,4096}, hw, generate_key_pair
  ECDSA-KEY-PAIR-GEN, keySize={224,521}, hw, generate_key_pair, EC F_P, EC OID, EC uncompressed
  SHA-1-HMAC, keySize={1,512}, hw, sign, verify
  GENERIC-SECRET-KEY-GEN, keySize={1,1024}, hw, generate
  SHA256-HMAC, keySize={1,512}, hw, sign, verify
  SHA384-HMAC, keySize={1,1024}, hw, sign, verify
  SHA512-HMAC, keySize={1,1024}, hw, sign, verify
  ECDSA, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDSA-SHA1, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDH1-DERIVE, keySize={224,521}, hw, derive, EC F_P, EC OID, EC uncompressed
  RSA-PKCS-OAEP, keySize={2048,4096}, hw, encrypt, decrypt
  mechtype-0xD9554204, keySize={128,256}, hw, encrypt, decrypt, wrap, unwrap
  ECDSA-SHA256, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDSA-SHA384, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDSA-SHA512, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest

$ pkcs11-tool --module yubihsm_pkcs11.so -L
Available slots:
Slot 0 (0x0): YubiHSM Connector localhost
  token label        : YubiHSM
  token manufacturer : Yubico (www.yubico.com)
  token model        : YubiHSM
  token flags        : login required, rng, token initialized, PIN initialized
  hardware version   : 2.20
  firmware version   : 2.20

**Comment by qpernil** [comment]
The AES support requires a 2.3.0 device, I'm afraid. Earlier firmwares didn't support it.

**Comment by gilweis** [comment]
Can someone with a new firmware version post the same test here?

**Comment by qpernil** [comment]
pkcs11-tool --module /usr/local/lib/pkcs11/yubihsm_pkcs11.dylib -M
Using slot 0 with a present token (0x0)
Supported mechanisms:
  RSA-PKCS, keySize={2048,4096}, hw, encrypt, decrypt, sign, verify
  SHA1-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  SHA256-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  SHA384-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  SHA512-RSA-PKCS, keySize={2048,4096}, hw, sign, verify
  RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA1-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA256-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA384-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  SHA512-RSA-PKCS-PSS, keySize={2048,4096}, hw, sign, verify
  RSA-PKCS-KEY-PAIR-GEN, keySize={2048,4096}, hw, generate_key_pair
  ECDSA-KEY-PAIR-GEN, keySize={224,521}, hw, generate_key_pair, EC F_P, EC OID, EC uncompressed
  SHA-1-HMAC, keySize={1,512}, hw, sign, verify
  GENERIC-SECRET-KEY-GEN, keySize={1,1024}, hw, generate
  SHA256-HMAC, keySize={1,512}, hw, sign, verify
  SHA384-HMAC, keySize={1,1024}, hw, sign, verify
  SHA512-HMAC, keySize={1,1024}, hw, sign, verify
  ECDSA, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDSA-SHA1, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDH1-DERIVE, keySize={224,521}, hw, derive, EC F_P, EC OID, EC uncompressed
  RSA-PKCS-OAEP, keySize={2048,4096}, hw, encrypt, decrypt
  mechtype-0xD9554204, keySize={128,256}, hw, encrypt, decrypt, wrap, unwrap
  ECDSA-SHA256, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDSA-SHA384, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  ECDSA-SHA512, keySize={224,521}, hw, sign, verify, EC F_P, EC OID, EC uncompressed
  AES-KEY-GEN, keySize={16,32}, hw, generate
  AES-ECB, keySize={16,32}, hw, encrypt, decrypt
  AES-CBC, keySize={16,32}, hw, encrypt, decrypt
  AES-CBC-PAD, keySize={16,32}, hw, encrypt, decrypt
  SHA-1, digest
  SHA256, digest
  SHA384, digest
  SHA512, digest

**Comment by gilweis** [comment]
Thanks!
What is the output for:
pkcs11-tool --module /home/g/work/yubihsm-shell/build/pkcs11/yubihsm_pkcs11.so -L

**Comment by qpernil** [comment]
There is no released firmware with AES support yet, so I don't have any interesting output to show you.

**Comment by gilweis** [comment]
Thanks,
If so, I suggest writing in the CHANGELOG that the actions "Add support for symmetric encryption, AES-ECB and AES-CBC"  are not supported on firmware 2.2 and below.

**Comment by qpernil** [comment]
That will be corrected, thanks for the suggestion. Closing this issue now as solved, please open a new one if needed.
