### ISSUE TITLE
Can't import certificate into YubiHSM 2 using yubihsm_pkcs11.so

### ISSUE THREAD

**Issue by misodengaku** [Yubico/yubihsm-shell#336]
I did tried import certificate to YubiHSM 2 with pkcs11-tool. But failed to import because `error: PKCS11 function C_CreateObject failed: rv = CKR_ATTRIBUTE_VALUE_INVALID (0x13)` error.
Upon closer inspection with YUBIHSM_PKCS11_DBG set to 1, the error `Boolean truth check failed for attribute 0x2` was printed.

```
$ YUBIHSM_PKCS11_DBG=1 pkcs11-tool --module /usr/local/lib/pkcs11/yubihsm_pkcs11.so -l -p 'xxxxxxxxxx' --write-object cert.der --id xxxxxxxxxx --type cert
[P11 - INF 15:36:55.772240] yubihsm_pkcs11.c:266 (C_Initialize): Found 1 configured connector(s)
[P11 - INF 15:36:55.782914] yubihsm_pkcs11.c:362 (C_Initialize): Found 1 usable connector(s)
[P11 - INF 15:36:55.782929] yubihsm_pkcs11.c:364 (C_Initialize): Found 0 configured device public key(s)
[P11 - INF 15:36:55.782937] yubihsm_pkcs11.c:520 (C_GetSlotList): Total number of slots is 1
[P11 - INF 15:36:55.782944] yubihsm_pkcs11.c:523 (C_GetSlotList): Can return 1 slot(s)
[P11 - INF 15:36:55.782955] yubihsm_pkcs11.c:548 (C_GetSlotList): Returning slot 0
Using slot 0 with a present token (0x0)
[P11 - INF 15:36:55.782976] yubihsm_pkcs11.c:906 (C_OpenSession): Allocated session 1
[P11 - INF 15:36:55.918422] yubihsm_pkcs11.c:1661 (C_CreateObject): Object will be stored with length 1049
[P11 - ERR 15:36:55.918440] yubihsm_pkcs11.c:1689 (C_CreateObject): Boolean truth check failed for attribute 0x2
error: PKCS11 function C_CreateObject failed: rv = CKR_ATTRIBUTE_VALUE_INVALID (0x13)
Aborting.
```

I checked yubihsm_pkcs11.c and it appears thet CKA_PRIVATE(attribute 0x2) is required to be `true`. However, pkcs11-tool forces CKA_PRIVATE to be `false` when writing certificates.

https://github.com/Yubico/yubihsm-shell/blob/master/pkcs11/yubihsm_pkcs11.c#L1684-L1693

https://github.com/OpenSC/OpenSC/blob/e58bca0a33e1e972728902566ee2641c5f1430d0/src/tools/pkcs11-tool.c#L4042

As a test, I rewrote yubihsm_pkcs11.c to not check the value of CKA_PRIVATE. The import into YubiHSM succeeded and also certificate is stored in a private state 
(execute `pkcs11-tool --module yubihsm_pkcs11.so -O` without a login, the object is not visible).

Given the behavior of YubiHSM, it seems correct to require CKA_PRIVATE to be `true`, but it seems odd to reuire it to be private due to the nature of the certificate object.

Does anyone understand the background behind such an implementation? Also, is there any chance that improvements could be accepted that would bypass this check?

**Comment by aveenismail** [comment]
The reason certificates are not "public" objects is that **all** communication with the YubiHSM2 is encrypted. That's why authentication is required to access any object, including certificates.

As for the pkcs11-tool command, have you tried to use the `--private` flag? It should set CKA_PRIVATE value to true.

**Comment by misodengaku** [comment]
> As for the pkcs11-tool command, have you tried to use the --private flag? It should set CKA_PRIVATE value to true.

Yes, I already tried the --private flag and it did not help.
When using the write-object command, it seems that the --private flag only works for [CKO_PUBLIC_KEY](https://github.com/OpenSC/OpenSC/blob/e58bca0a33e1e972728902566ee2641c5f1430d0/src/tools/pkcs11-tool.c#L4196-L4199), [CKO_SECRET_KEY](https://github.com/OpenSC/OpenSC/blob/e58bca0a33e1e972728902566ee2641c5f1430d0/src/tools/pkcs11-tool.c#L4292-L4295) and [CKO_DATA](https://github.com/OpenSC/OpenSC/blob/e58bca0a33e1e972728902566ee2641c5f1430d0/src/tools/pkcs11-tool.c#L4356-L4359).

Also, after referring to the PKCS#11 specification, it appears that CKA_PRIVATE is an attribute that can be used for all objects, so the current pkcs11-tool behavior of not accepting the --private flag when writing certificate objects It seems strange to me.

This Issue is closed as it seems like something that should be asked in the OpenSC project. Thank you for your answer.
