### ISSUE TITLE
Add support for CKA_EXTRACTABLE for PKCS11 imported certificates

### ISSUE THREAD

**Issue by driseley** [Yubico/yubihsm-shell#341]
It would be nice if we could configure if PKCS11 imported X509 certificates to have the `exportable-under-wrap` capability set.  
This would be done by setting the `CKA_EXTRACTABLE` attribute on the `C_CreateObject` call

Currently attempting to set this fails with the following error (against 2.4.0):

```
yubihsm_pkcs11.c:1739 (C_CreateObject): Invalid attribute type in key template: 0x162
```

I think this just needs a one line change to add support for `CKA_EXTRACTABLE` for `CKO_CERTIFICATE` objects, I'll submit a PR for this.

**Comment by qpernil** [comment]
Thanks for the contribution!
