### ISSUE TITLE
Error running keytool on windows with YubiHSM

### ISSUE THREAD

**Issue by medhost-nwatson** [Yubico/yubihsm-shell#374]
C:\windows\system32>keytool -list -keystore NONE -storetype PKCS11 -providerClass sun.security.pkcs11.SunPKCS11 -providerArg C:\yubihsm\sun_yubihsm2_pkcs11.conf -storepass <redacted> -v
keytool error: java.security.ProviderException: Initialization failed
java.security.ProviderException: Initialization failed
        at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:381)
        at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:112)
        at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11$1.run(SunPKCS11.java:109)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.configure(SunPKCS11.java:109)
        at java.base/sun.security.tools.KeyStoreUtil.loadProviderByName(KeyStoreUtil.java:273)
        at java.base/sun.security.tools.KeyStoreUtil.loadProviderByClass(KeyStoreUtil.java:306)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:822)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:412)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:405)
Caused by: java.io.IOException: The specified procedure could not be found.
C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll
        at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.connect(Native Method)
        at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.<init>(PKCS11.java:147)
        at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.getInstance(PKCS11.java:160)
        at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:318)
        ... 9 more

Contents of sun_yubihsm2_pkcs11.conf
`name = yubihsm-pkcs11
library = C:\Program Files\Yubico\YubiHSM Shell\bin\pkcs11\yubihsm_pkcs11.dll
attributes(*, CKO_PRIVATE_KEY, CKK_RSA) = {
  CKA_SIGN=true
}`

Contents of yubihsm_pkcs11.conf
`connector = http://10.128.50.203:12345`

I have the YUBIHSM_PKCS11_CONF environment variable set to the path to yubihsm_pkcs11.conf. Running Corretto 11 for JVM. I'm not sure what else to check.

**Comment by aveenismail** [comment]
That should be sufficient.

2 suggestions:
* Are there yubihsm-shell files in C:\Windows\System32? If yes, remove them and try again
* If the above doesn't work, add debug lines to `yubihsm_pkcs11.conf` so the content would look like the following, then try again and copy the debug output here. It could be helpful to see if it finds the libraries in the first place.

```
connector = http://10.128.50.203:12345
debug
dinout
libdebug
```

**Comment by medhost-nwatson** [comment]
The only yubihsm related file I see in System32 is for the KSP CNG which we also need. 
<img width="648" alt="Screenshot 2023-12-11 at 3 41 44 PM" src="https://github.com/Yubico/yubihsm-shell/assets/13066434/3465f23b-39d0-419e-9e3f-79388bed5729">

I already have the debug lines added in my yubihsm_pkcs11.conf. Is there somewhere else I need to look for the debug output other than what I get when running keytool?

**Comment by medhost-nwatson** [comment]
Yubico Support had me try version 2.3.2 of the YubiHSM-shell from that 2022.6 release on yubico website and that version does not have the issue. It's working successfully and I see all the debug output when running keytool. So it seems like some change introduced after that version caused the issue.

**Comment by medhost-nwatson** [comment]
It will take me a while to be able to do that. Now that we have this working with the older version we need to finish implementing code signing and then I can come back to this and work on trying to get latest versions going. Several days at least. 

I can tell you that this was a fresh deployment of Windows Server 2022 that had never had any YubiHSM software installed previously and that we had only downloaded the latest package from Yubico website and installed the CNG and yubihsm-shell. So if there is an older version of libyubihsm on there it would have had to be one of those that put it there I think.

**Comment by aveenismail** [comment]
I understand. Please let us know how it goes.

The yubihsm-sdk is basically a collection of different softwares, among which are the yubihsm-shell and the yubihsm-cngprovider installers. libyubihsm.dll is part of the yubihsm-shell software/installer and that same installer is included in the yubihsm-sdk software packge.

Can I ask, if this is a completely new installation, how come you installed an older version of yubihsm-shell but the newest yubihsm-sdk? The good news is that if you're using it for code signing then you're probably using the asymmetric key functions and these haven't changed in the latest releases. However, I have to say that I do find it strange that yubihsmksp.dll ended up in System32 while libyubihsm.dll somewhere else. I look forward to your investigation.

**Comment by aveenismail** [comment]
Apologies for taking this long to figure it out. I believe your correspondence with Yubico support explained that the CNG provider installs its own version of libyubihsm in system32 and that leads to a mismatch between the libyubihsm version that the CNG provider vs yubihsm_pkcs11 depends on.

There is now a new YubiHSM SDK release (available on https://developers.yubico.com/YubiHSM2/Releases/) where the CNG provider is rebuilt using the latest libyubihsm. We will also be making sure that this mismatch does not occur again in future releases.

**Comment by medhost-nwatson** [comment]
Yes we found files in System32 as you suggested but they were named a little differently and I guess windows search didn't find them when I looked before. Thanks for your help.
