### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by AJH16** [Yubico/yubihsm-shell#402]
The build documentation indicates needing to get files from a source release package, but does not mention where to find said package.   Seemingly unable to build the Windows version without this.

**Comment by AJH16** [comment]
For anyone else that comes across this, if you use a linux system to run ./resources/make_src_dist.sh $VERSION, it will spit out a source distribution for you.

**Comment by aveenismail** [comment]
The source release for yubihsm-shell is available here: https://developers.yubico.com/yubihsm-shell/Releases/
