### ISSUE TITLE
C_WrapKey in yubihsm_pkcs11.c is returning too many bytes

### ISSUE THREAD

**Issue by fiercelybearded** [Yubico/yubihsm-shell#407]
I'm working on a solution where I am generating EC signing keys in the YubiHSM and then wrapping/exporting them from the module. What I am seeing is that when I use the PKCS#11 library to do the aes-ccm-256 object wrapping, I am getting back 15 extra bytes of 0s. When I use the YubiHSM Shell tool, I get the correct amount of bytes. I found this issue because I wrap the key with PKCS#11, and then later when I need to use it, I am unwrapping it back into the module. However, I am getting an error message like so:

```
yubihsm_pkcs11.c:5542 (C_UnwrapKey): Unwrapping failed: Malformed command / invalid data
```

I compared outputs different methods of wrapping. Here is a hexdump of what it looks like with a PKCS#11 wrap operation:

```
00000000  2a de bb 6a 9a 00 00 00  00 00 00 00 01 38 1f 47  |*..j.........8.G|
00000010  eb aa 05 91 2b 04 25 91  4c 24 e3 9b b7 f7 40 5b  |....+.%.L$....@[|
00000020  08 c6 42 2d 91 51 88 f2  d9 9e 7f de e2 fa 92 2c  |..B-.Q.........,|
00000030  3a 92 00 c2 6b d2 8c 38  6b d9 40 89 1c 32 9d 93  |:...k..8k.@..2..|
00000040  43 7a 2e e3 eb 34 0b 6b  ac 2d a9 05 a2 60 25 40  |Cz...4.k.-...`%@|
00000050  49 a2 c2 34 12 fe c6 3b  b3 c2 fc 6d 85 70 c0 c6  |I..4...;...m.p..|
00000060  06 7e 55 f4 d0 d5 28 34  56 e5 96 cf 7f a0 6b d5  |.~U...(4V.....k.|
00000070  ee d1 48 b0 b0 a3 a6 f7  9e 4f 8e c2 1c 45 d4 e6  |..H......O...E..|
00000080  e2 78 91 ac 25 15 5d e1  79 09 48 23 e8 09 c3 6b  |.x..%.].y.H#...k|
00000090  ed cb f2 92 e5 26 eb ea  fc 3e 25 03 28 f6 9b 73  |.....&...>%.(..s|
000000a0  33 0a 24 22 f3 1c 4a a4  79 0d 43 3e 3f 4b 18 e6  |3.$"..J.y.C>?K..|
000000b0  ca dc 45 ae c0 dc b4 7a  0e a9 56 be 3a 70 3b 6c  |..E....z..V.:p;l|
000000c0  a7 7b 85 a8 8a ed ee 32  08 39 f3 78 2b d5 cb f2  |.{.....2.9.x+...|
000000d0  66 74 9a 7c 72 fa 41 a3  03 30 9a 92 95 a7 32 bb  |ft.|r.A..0....2.|
000000e0  d2 b5 02 65 8b df 70 c9  00 00 00 00 00 00 00 00  |...e..p.........|
000000f0  00 00 00 00 00 00 00                              |.......|
```

And here is a the hexdump of the wrapped key using YubiHSM Shell:

```
00000000  2a de bb 6a 9a 00 00 00  00 00 00 00 03 05 33 03  |*..j..........3.|
00000010  17 2e 12 72 f6 13 f3 f0  c3 9c 8e 25 68 4a 7a 9d  |...r.......%hJz.|
00000020  c8 93 1b a1 cc 7e c1 6b  70 41 e5 1c 99 5c 6f 3b  |.....~.kpA...\o;|
00000030  e7 00 ef ff 49 49 e5 fd  1e cb 25 cc 75 53 af 10  |....II....%.uS..|
00000040  05 27 da ea db 13 23 27  18 fb 52 68 63 c9 62 bb  |.'....#'..Rhc.b.|
00000050  93 ed 5c 84 72 17 8e 26  33 22 60 27 72 25 97 5c  |..\.r..&3"`'r%.\|
00000060  ec c3 96 a9 df 8f 14 40  5c da 6d ad f5 78 8f e1  |.......@\.m..x..|
00000070  4b c9 86 9a 63 23 11 16  ba 0b 4e 62 d1 11 7a e4  |K...c#....Nb..z.|
00000080  26 50 72 2e b7 3e e7 09  70 c0 53 c5 cb 72 72 bc  |&Pr..>..p.S..rr.|
00000090  bd ae d3 b6 b8 21 35 c0  2e f3 27 d2 57 02 2a 47  |.....!5...'.W.*G|
000000a0  8c 66 c2 46 0c ef ed 10  4a 0a e2 d6 01 e1 5c b6  |.f.F....J.....\.|
000000b0  66 06 a0 d9 e5 a2 d1 a2  b3 fe 06 94 0d aa c8 01  |f...............|
000000c0  e9 a9 39 5f 2d f1 99 e5  5c d4 67 a9 f1 3c 18 e3  |..9_-...\.g..<..|
000000d0  26 17 33 fb a1 e8 eb 25  e8 47 cb ea a3 df 0b 03  |&.3....%.G......|
000000e0  63 0b d8 aa 41 2f 14 a8                           |c...A/..|
```

At first I thought maybe it was some kind of encoding issue that I introduced, but I can even see a message from yubihsm_pkcs11.c that says:
```
yubihsm_pkcs11.c:5403 (C_WrapKey): Calculated that wrapping will need 247 bytes
```

But the output from the YubiHSM Shell wrap operation is only 232 bytes (after it is base64 decoded). I have found that when I strip off the last 15 bytes of what is returned from the PKCS#11 wrap operation, I can use it in an Unwrap operation successfully. 

I have only tried this with EC secp256r1 and secp384r1 keys. This is on version 2.4.2 of the client, and I am using the YubiHSM2 FIPS with FIPS mode turned on, using an Intel Mac. I have used aes-ccm-128 and aes-ccm-256 and both give 15 extra bytes.

**Comment by aveenismail** [comment]
Thank you for bringing the issue to our attention. However, we are unable to re-produce the error neither with 2.4.2 version or later ones.

Could the issue be on the side of the client calling the PKCS11 module functions? How are you interacting with the yubihsm_pkcs11?

**Comment by fiercelybearded** [comment]
Seems to be an issue using the Rust client I'm using.
