### ISSUE TITLE
Can't backup YubiHSM 2 using YubiHSM Shell - Wrong permissions for operation

### ISSUE THREAD

**Issue by Nikolay-everstake** [Yubico/yubihsm-shell#409]
I have tried to check YubiHSM 2 backup using exactly the instructions
https://docs.yubico.com/hardware/yubihsm-2/hsm-2-user-guide/hsm2-backup-restore.html#hsm2-backup-restore-label
and got this error - Failed to get wrapped object: Wrong permissions for operation.
I used default authentication key with default password but it didn't work.
yubihsm-shell 2.4.2
get deviceinfo
Version number:         2.3.2
Serial number:          26300602
Log used:               2/62
Supported algorithms:   rsa-pkcs1-sha1, rsa-pkcs1-sha256, rsa-pkcs1-sha384,
                        rsa-pkcs1-sha512, rsa-pss-sha1, rsa-pss-sha256,
                        rsa-pss-sha384, rsa-pss-sha512, rsa2048,
                        rsa3072, rsa4096, ecp256,
                        ecp384, ecp521, eck256,
                        ecbp256, ecbp384, ecbp512,
                        hmac-sha1, hmac-sha256, hmac-sha384,
                        hmac-sha512, ecdsa-sha1, ecdh,
                        rsa-oaep-sha1, rsa-oaep-sha256, rsa-oaep-sha384,
                        rsa-oaep-sha512, aes128-ccm-wrap, opaque-data,
                        opaque-x509-certificate, mgf1-sha1, mgf1-sha256,
                        mgf1-sha384, mgf1-sha512, template-ssh,
                        aes128-yubico-otp, aes128-yubico-authentication, aes192-yubico-otp,
                        aes256-yubico-otp, aes192-ccm-wrap, aes256-ccm-wrap,
                        ecdsa-sha256, ecdsa-sha384, ecdsa-sha512,
                        ed25519, ecp224, rsa-pkcs1-decrypt,
                        ecp256-yubico-authentication, aes128, aes192,
                        aes256, aes-ecb, aes-cbc,

**Comment by Nikolay-everstake** [comment]
Some mistakes in doc

**Comment by RemiEC** [comment]
Hi ! 
Any additionnal info on this ? I encountered the same issue
