### ISSUE TITLE
yh_is_ec does not check all ECC algorithms

### ISSUE THREAD

**Issue by notdpate** [Yubico/yubihsm-shell#44]
yh_is_ec returns false for some of the new defines for ECC algorithms.

**Comment by klali** [comment]
What algorithms do you consider missing (a PR might be quicker). =)

**Comment by notdpate** [comment]
Apparently I had a key generated with a previous version of the SDK that reported the algorithm was of type ECDH, which is invalid.  This is not allowed in the current version, so the function appears to work as designed.
