### ISSUE TITLE
Cannot connect yubihsm2 without touch

### ISSUE THREAD

**Issue by yulidai** [Yubico/yubihsm-shell#48]
##### What's your problem?
I have bought three yubihsm2, the first key works fine. But the others yubihsm2 would not flash after plug in the computer.

##### Any other supplementary information?
Accidental discovery of keeping in touch with my finger after plugging into computer, it will be flash. Once my fingers are gone, re-touch will not work.

Perhaps double authentication needs to be turned off, but why not the first one?

**Comment by a-dma** [comment]
What versions are your devices?

Try making sure you plug the device without touching the golden rim (use a tissue or a pen). Some devices could become unresponsive if the touch sensor is held at insertion.

**Comment by yulidai** [comment]
It works after Using tissue, that's amazing...
