### ISSUE TITLE
Is it possible to stabilize the signature result?

### ISSUE THREAD

**Issue by yulidai** [Yubico/yubihsm-shell#50]
Is it possible to stabilize the signature result using `secp256k1`?

Every time i execute `client.sign_ecdsa(key_id, msg)` with the same `key_id` and `msg`, will get different results.  Sometimes it's even wrong.

Did I use the wrong api?

**Comment by yulidai** [comment]
I know the results will vary depending on the random number. But is it possible to stabilize the result like using software's method whose random number is depending on the `msg`?  Is there such a switch param?

**Comment by a-dma** [comment]
ECDSA is a non deterministic signature algorithm. RFC 6979 specifies how to get deterministic signatures but that is not implemented by the YubiHSM.

**Comment by yulidai** [comment]
But why sometimes there are wrong results?

**Comment by yulidai** [comment]
Now I am using the Secp256k1 library to verify by public key and signature information. I will sign again until it is correct.

**Comment by a-dma** [comment]
If your library expects a signature to be "canonical" like for example BitCoin does, then you could run into problems. One of the two components of the signature `s` can sometimes be larger than `N/2` (the order of the curve). If that's the case you need to reduce `s` by using the value `N - s` instead.

**Comment by yulidai** [comment]
Thanks, I will ponder over it again.  :)
