### ISSUE TITLE
Can we have signed releases?

### ISSUE THREAD

**Issue by Jakuje** [Yubico/yubihsm-shell#6]
The current version of https://developers.yubico.com/yubihsm-shell/ does not list the releases nor any signatures of the releases. Can this be added as it already exists for other projects?

Thanks.

**Comment by klali** [comment]
Thanks for the reminder. This was postponed in the rush to get everything out, I've just pushed the source releases for all involved projects (yubihsm-shell, yubihsm-connector, yubihsmrs, yubihsm-setup)
