### ISSUE TITLE
ed25519 support in PKCS#11 module

### ISSUE THREAD

**Issue by lumag** [Yubico/yubihsm-shell#75]
Could you please add support for ed25519 keys into your pkcs11 module?

**Comment by Jakuje** [comment]
For the record, the PKCS #11 3.0 now supports Ed25519 keys through a new key type:

https://www.oasis-open.org/news/announcements/four-pkcs-11-specifications-from-pkcs11-tc-approved-as-committee-specifications

**Comment by qpernil** [comment]
Ed25519 support will come when / if we update the PKCS11 module to support the PKCS#11 3.0 support. The underlying native library already supports it. As PKCS#11 is all about accessing the HSM in a standard way it doesn't make a lot of sense to add support based on a proprietary algorithm ID for example. Closing this issue now, please resubmit if needed.

**Comment by sonkkeli** [comment]
Any news on the support for this? We are also looking for a security key supporting PKCS11 3.0 spec.

**Comment by qpernil** [comment]
See https://github.com/Yubico/yubihsm-shell/pull/183

**Comment by qpernil** [comment]
And https://github.com/Yubico/yubico-piv-tool/pull/308

**Comment by sonkkeli** [comment]
Amazing, thanks qpernil@!
Do you have an idea on when these would be merged? :)

**Comment by qpernil** [comment]
A decision hasn't been made yet because we need to qualify the changes more, to be sure we actually implement what the spec requires. There are things missing as of now that we know of, but more could surface.

**Comment by roth-wine** [comment]
Hello,
Are there any updates yet on the process for supporting the PKCS11 3.0 spec?
