### ISSUE TITLE
Unencrypting wrapped key

### ISSUE THREAD

**Issue by pbostrom** [Yubico/yubihsm-shell#78]
I have exported a wrapped asymmetric key, and now I need to decrypt the key to use in an a different application outside of the YubiHSM2. Is there any documentation for the process of decrypting a wrapped key?

**Comment by a-dma** [comment]
This is similar to #74.

tl;dr it's not officially supported, but you can just AES-CCM decrypt a wrapped object to get its content. That however is in an internal format that is object-specific. In most cases this yields a usable key/object, provided that you know where the relevant data starts. In other cases there might be "some assembly required" that will make it hard (or at times even impossible) to just feed the data as is into some other tool or library.

**Comment by pbostrom** [comment]
> there might be "some assembly required"

That's what I was afraid of!
