### ISSUE TITLE
YubiHSM produces error -5 sometimes and sometimes not

### ISSUE THREAD

**Issue by Pymann** [Yubico/yubihsm-shell#81]
Hi Guys,

Sometimes the yubihsm does not execute operation and returns -5. But sometimes he does?
Is there any timing i have to fullfill? I tried to stabilize with sleep command, but it does not help.

i have following c-program:
```
#include <string.h>  
#include <stdlib.h>
#include <yubihsm.h>
#include "internal.h"
#include <assert.h>
#include <unistd.h>

static void print_yhrc(yh_rc yrc);


static void print_buffer(uint8_t *label, uint8_t *buffer, uint32_t len);


yh_rc yh_wrap_data(	uint16_t authkey, 
					const char* password, 
					const char* label,
					const char* domains, 
					uint16_t *wrapkey_id_p,
					uint8_t *data, 
					size_t *data_len,
					uint8_t *out, 
					size_t *out_len) {

	sleep(1);
    printf(password);printf("\n");
    printf(label);printf("\n");
	printf("%d",authkey);printf("\n");
    static yh_connector connector_arg;
	yh_connector *connector = &connector_arg;
	yh_session *session = NULL;
	yh_rc yrc = YHR_GENERIC_ERROR;

	//serial=0007550878
	const char *connector_url = "yhusb://";
	yrc = yh_init();
	assert(yrc == YHR_SUCCESS);

	yrc = yh_init_connector(connector_url, &connector);
	assert(yrc == YHR_SUCCESS);

	yrc = yh_connect(connector, 0);
	if (yrc == YHR_SUCCESS) {
		printf("Connected!\n");
		//printf(yh_strerror(yrc));
	} else {
		printf("Connect error: %02d\n", (int)yrc);
	}

	yrc = yh_create_session_derived(connector, authkey, password,
		                  sizeof(password), false, &session);
	print_yhrc(yrc);

	yrc = yh_authenticate_session(session);
	print_yhrc(yrc);

	uint8_t session_id;
	yrc = yh_get_session_id(session, &session_id);
	print_yhrc(yrc);
	if (yrc == YHR_SUCCESS) {
		printf("Successfully established session %02d\n", session_id);
	} else {
		return yrc;
	}

    uint16_t domain_arg2;
	uint16_t *domain = &domain_arg2;
	printf("string_to_domains\n");	
	yrc = yh_string_to_domains(domains, domain);
	print_yhrc(yrc);

    yh_capabilities wrapkey_cap_arg;
	yh_capabilities *wrapkey_cap = &wrapkey_cap_arg;
	printf("WrapKey caps\n");
	yrc = yh_string_to_capabilities("exportable-under-wrap|unwrap-data|wrap-data", wrapkey_cap);
	print_yhrc(yrc);
	uint16_t key_arg = 0; //let device generate id
	uint16_t* key_p = &key_arg;
	yh_capabilities yh_cap_arg;
	yh_capabilities *yh_cap = &yh_cap_arg;
	printf("Key caps\n");
	yrc = yh_string_to_capabilities("exportable-under-wrap|unwrap-data|wrap-data", yh_cap);
	print_yhrc(yrc);

	/*yh_rc yh_util_generate_wrap_key(yh_session *session, uint16_t *key_id,
									const char *label, uint16_t domains,
									const yh_capabilities *capabilities,
									yh_algorithm algorithm,
									const yh_capabilities *delegated_capabilities);*/
	sleep(1);
	yrc = yh_util_generate_wrap_key(session, wrapkey_id_p,
                              label, *domain,
                              wrapkey_cap,
                              YH_ALGO_AES128_CCM_WRAP,
                              yh_cap);

	printf("GeneratedWrapKey ID: %02d\n", *wrapkey_id_p);
	print_yhrc(yrc);
	


	/*yh_rc yh_util_wrap_data(	yh_session *session, 
								uint16_t key_id, 
								const uint8_t *in,
                        		size_t in_len, 
								uint8_t *out, 
								size_t *out_len);*/
	size_t wrapout_len=10000;
	size_t *wrapout_len_p=&wrapout_len;
	uint8_t wrapoutcome[10000] = {};
	printf("Wrap-Data\n");	
	print_buffer("Not Wrapped", data, *data_len);	
	sleep(1);	
	yrc = yh_util_wrap_data(session, *wrapkey_id_p,
							data,
							*data_len,
							wrapoutcome,
							wrapout_len_p);

    print_yhrc(yrc);
	if (yrc == YHR_SUCCESS) {
		print_buffer("Wrapped", wrapoutcome, *wrapout_len_p);
	}
	size_t unwrapout_len=10000;
	size_t *unwrapout_len_p=&wrapout_len;
	uint8_t unwrapoutcome[10000] = {};
	sleep(1);
	/*yh_rc yh_util_unwrap_data(yh_session *session, uint16_t key_id,
                          const uint8_t *in, size_t in_len, uint8_t *out,
                          size_t *out_len);*/
	yrc = yh_util_unwrap_data(session, *wrapkey_id_p,
                          wrapoutcome, *wrapout_len_p, 
						  unwrapoutcome, unwrapout_len_p);
	print_yhrc(yrc);
	if (yrc == YHR_SUCCESS) {
		print_buffer("Unwrapped", unwrapoutcome, *unwrapout_len_p);	
	}
	out = (uint8_t*)memcpy(out,unwrapoutcome,*unwrapout_len_p);
	*out_len = *unwrapout_len_p;
	sleep(1);
	yrc = yh_util_close_session(session);
	print_yhrc(yrc);
	yrc = yh_disconnect(connector);
	print_yhrc(yrc);

	yrc = yh_exit();

	sleep(1);

	return yrc;
}


static void print_yhrc(yh_rc yrc) {
    if (yrc == YHR_SUCCESS) {

	} else {
		printf("Error: %02d\n", (int)yrc);
	}
}


static void print_buffer(uint8_t *label, uint8_t *buffer, uint32_t len) {
	printf(label);
	printf("\nBuffer len: %02d\n", len);
	for(uint32_t i = 0; i<len; i++) {
		printf("0x%02x,", *buffer);
		buffer++;
	}
	printf("\n");
}
```

**Comment by a-dma** [comment]
The return value `-5` means invalid parameters. Try checking that your session hasn't expired or that you're not passing in a stale session.

If that's not enough, before we can help you further please provide a minimal reproducible example with the following:
- add a `main` function
- remove any unnecessary and commented out code
- state which function call is causing you problems

**Comment by Pymann** [comment]
I use this function in another main-function.
Is there any function, to check status of the session?

**Comment by a-dma** [comment]
No, not explicitly.

Can you tell us which line is returning an error?

**Comment by Pymann** [comment]
Its:
```
yrc = yh_util_wrap_data(session, *wrapkey_id_p,
							data,
							*data_len,
							wrapoutcome,
							wrapout_len_p);
```

... but as I said, its just sometime returning -5 and sometime its working.
And sleep commands do not help ...

Can you give any information, how fast you can connect get session and disconnect to the device?
Is there any timing. I reaad on your homepage, that some operations, take a little bit longer.

**Comment by Pymann** [comment]
I solved the problem by destroying the session after closing it:
yrc = yh_destroy_session(&session);

If you dont close the session the session, seems to be blocked and cant be reestablished, unless it expires after sometime.

Therefore program sometimes return -5 and sometimes not.

**Comment by nevun** [comment]
For the internet archives maybe this would be helpful:

From https://developers.yubico.com/YubiHSM2/Concepts/Session.html

"On a single YubiHSM 2 it is possible to establish up to 16 independent and concurrent Sessions. Note that while multiple concurrent Sessions can be active at a given time, the device still serves as a rendezvous point. This means that time-consuming operations, like generating a long RSA key, will block commands in other Sessions. Sessions are addressed with a number in the range [0-15].

Sessions have an expiration period of 30 seconds of inactivity in order to prevent resource starvation. After such a period, the device will consider a Session inactive and will move it to the pool of re-usable Sessions. Whenever a command is executed on a given Session, the inactivity timer is reset, meaning that if a Session is being constantly used then it will not expire."

**Comment by Pymann** [comment]
> For the internet archives maybe this would be helpful:
> 
> From https://developers.yubico.com/YubiHSM2/Concepts/Session.html
> 
> "On a single YubiHSM 2 it is possible to establish up to 16 independent and concurrent Sessions. Note that while multiple concurrent Sessions can be active at a given time, the device still serves as a rendezvous point. This means that time-consuming operations, like generating a long RSA key, will block commands in other Sessions. Sessions are addressed with a number in the range [0-15].
> 
> Sessions have an expiration period of 30 seconds of inactivity in order to prevent resource starvation. After such a period, the device will consider a Session inactive and will move it to the pool of re-usable Sessions. Whenever a command is executed on a given Session, the inactivity timer is reset, meaning that if a Session is being constantly used then it will not expire."

Its has nothing to do with my problem. My problem was that not-destroyed session blocked operations.

**Comment by nevun** [comment]
yeah, you are right. Read to fast :]
