### ISSUE TITLE
release for ubuntu 20.04

### ISSUE THREAD

**Issue by vadave** [Yubico/yubihsm-shell#87]
I've attempted to build `yubihsm-connector` and `yubihsm-shell` on Ubuntu 20.04 and I seem to have gotten it to build successfully, but I'm unable to actually get it to connect okay. I can see the HSM is being recognized by the OS (in the output of `dmesg`), but when I try to actually open a session I see `failed usb proxy` with `device not found` in the debug output. 

I'm sure I've missed something in the build/install process that's being handled by the packages you provide. I'd love to just have a supported 20.04 release. Is there any chance you could get a 20.04 build added at some point?

**Comment by a-dma** [comment]
Yes, an official release for 20.04 is definitely missing. In the meanwhile, have you started the connector as root or alternatively does your user have access to the USB device (you need a udev rule for that, sample one at https://developers.yubico.com/YubiHSM2/Component_Reference/yubihsm-connector/, change it to your user)?

Doing a GET request to `/connector/status` will report whether or not the connector can see the device.

**Comment by vadave** [comment]
`/connector/status` (with `yubihsm-connector` run by `root`) yields: 

```
status=NO_DEVICE
serial=*
version=2.2.0
pid=342922
address=localhost
port=12345
```

output of dmesg shows 

```
[344829.532486] usb 1-13: new full-speed USB device number 13 using xhci_hcd
[344829.681815] usb 1-13: New USB device found, idVendor=1050, idProduct=0030, bcdDevice= 2.11
[344829.681821] usb 1-13: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[344829.681824] usb 1-13: Product: YubiHSM
[344829.681827] usb 1-13: Manufacturer: Yubico
[344829.681830] usb 1-13: SerialNumber: <my_serial_number>
```

**Comment by a-dma** [comment]
could you run the connector with `-d`? What kind of output do you see in that case after sending a GET request?

**Comment by vadave** [comment]
full output looks like this:
```
DEBU[0000] preflight complete                            cert= config= key= pid=344440 seccomp=false serial= syslog=false timeout=0s version=2.2.0
DEBU[0000] takeoff                                       TLS=false listen="localhost:12345" pid=344440
DEBU[0022] reopening usb context                         Correlation-ID=7090e753-c247-46cc-8108-9559d406e7f9 why="status request"
DEBU[0022] usb context not yet open                      Correlation-ID=7090e753-c247-46cc-8108-9559d406e7f9
DEBU[0023] Couldn't read serial number from device       Correlation-ID=7090e753-c247-46cc-8108-9559d406e7f9 Device="vid=1050,pid=0030,bus=1,addr=13"
WARN[0023] status failed to open usb device              X-Request-ID=7090e753-c247-46cc-8108-9559d406e7f9 error="device not found"
```
as previously mentioned, the thing that jumped out to me is the `failed to open usb device` and `device not found` bits. I'm also seeing this show up, which makes me think something's mucked with my build (even though it appeared to build fine - once I sorted out the dependencies):
```
2020/07/10 09:02:12 handle_events: error: libusb: interrupted [code -10]
```

**Comment by a-dma** [comment]
yes, that is what you get when the connector can't find the device at all, for example you will get the same error if you unplug the device.

Are you using any kind of virtualization where the device has to be passed through? Was everything working before or is this your first attempt?

Two things to try, one of which is slightly weird...
a) don't start a connector and insted run `sudo ./src/yubihsm-shell --connector=yhusb:// -v127 -a get-device-info` if this works we know that something is up with the connector
b) there's a sporadic electrical issue with 2.1.1 devices (which you seem to have), try re-plugging the device without touching the golden sensor, use some cloth/paper to push it in, and re-run the commands above

**Comment by vadave** [comment]
Amazing. I tried a) first but the output appeared to hang. So I unplugged the device and used a lint-free cloth to hold it while I plugged it back in...and now it works. Kudos for the "slightly weird" fix.....I never would have come up with that. 

Now (with the connector running), I'm getting the following from `/connector/status`:
```
status=OK
serial=*
version=2.2.0
pid=348133
address=localhost
port=12345
```

**Comment by snj33v** [comment]
Can we update on this ?, which tag/commit should I build on ?

**Comment by a-dma** [comment]
The latest version of the SDK includes a build for Ubuntu 20.04.

https://developers.yubico.com/YubiHSM2/Releases/
