### ISSUE TITLE
memory resource leaks in yubihsm-shell CLI tool 

### ISSUE THREAD

**Issue by invd** [Yubico/yubihsm-shell#88]
### Part no. 1
During recent fuzzing of yubihsm-shell, I've noticed that the following memory allocated in the `main()` is not properly `free`'d in the cleanup phase:

https://github.com/Yubico/yubihsm-shell/blob/130a1cf65d7bedefa7c700655884b3e75eb5223d/src/main.c#L1791
https://github.com/Yubico/yubihsm-shell/blob/130a1cf65d7bedefa7c700655884b3e75eb5223d/src/main.c#L1798

The `main_exit` section doesn't touch it:
https://github.com/Yubico/yubihsm-shell/blob/130a1cf65d7bedefa7c700655884b3e75eb5223d/src/main.c#L2718-L2733

### Part no. 2
While looking at the `pcc_failure` cleanup section of the related `parse_configured_connectors()` function, I've noticed the following line, which I think is flawed and also leads to some resource leakage:
https://github.com/Yubico/yubihsm-shell/blob/130a1cf65d7bedefa7c700655884b3e75eb5223d/src/main.c#L1713

It doesn't make sense to overwrite `ctx->connector_list` multiple times with `NULL` and then try to `free()` it.
The line should probably have been `ctx->connector_list[i] = NULL;`

### Comment
Given the context, I do not consider either issue security related. The functional impact of the leaks is likely also low for regular CLI operation.

**Comment by nevun** [comment]
Thank you for the report. You are correct that this is a memory leak and no 2 is for sure a mistake.

Would you agree the following patch fixes it?

```
diff --git a/src/main.c b/src/main.c
index 7e488ad..1431ea7 100644
--- a/src/main.c
+++ b/src/main.c
@@ -1710,7 +1710,7 @@ static int parse_configured_connectors(yubihsm_context *ctx, char **connectors,
 pcc_failure:
   for (int i = 0; i < ctx->n_connectors; i++) {
     free(ctx->connector_list[i]);
-    ctx->connector_list = NULL;
+    ctx->connector_list[i] = NULL;
   }
 
   free(ctx->connector_list);
@@ -2737,5 +2737,14 @@ main_exit:
   ctx.state = NULL;
 #endif
 
+  if (ctx.connector_list != NULL) {
+    for (int i = 0; i < ctx.n_connectors; i++) {
+      free(ctx.connector_list[i]);
+      ctx.connector_list[i] = NULL;
+    }
+    free(ctx.connector_list);
+    ctx.connector_list = NULL;
+  }
+
   return rc;
 }
```

**Comment by invd** [comment]
@nevun:
I think `ctx.n_connectors = 0;` can be added to the second part of the patch, otherwise things look good, I'll test the exact code in the next days.
